// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AIReportRequest1
{
    public Guid AIRequestId { get; set; }

    public Guid TenantId { get; set; }

    public string CreatedBy { get; set; }

    public string ParametersJson { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }
}