// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AIReportRequest
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public int ReportType { get; set; }

    public DateTime FromDt { get; set; }

    public DateTime ToDt { get; set; }

    public string ReportParametersJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public DateTime? OutcomeDt { get; set; }

    public string Outcome { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}