// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AIReportResult
{
    public Guid ResultId { get; set; }

    public Guid AIRequestId { get; set; }

    public Guid TenantId { get; set; }

    public string ReportName { get; set; }

    public string ReportBlobUrl { get; set; }

    public string Status { get; set; }

    public DateTime CompletedAt { get; set; }
}