// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class APISECollectionTestConfig
{
    public Guid Id { get; set; }

    public Guid APISECollectionId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string TestConfigJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceScheduleId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public Guid DivisionId { get; set; }

    public string USERID { get; set; }

    public virtual APISECollection APISECollection { get; set; }

    public virtual AssuranceSchedule AssuranceSchedule { get; set; }

    public virtual AssuranceTemplate AssuranceTemplate { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual AspNetUser USER { get; set; }
}