// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class APISESWAGGER
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string SWAGGERJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public virtual ICollection<APISECollectionSWAGGERSKeyValue> APISECollectionSWAGGERSKeyValues { get; set; } = new List<APISECollectionSWAGGERSKeyValue>();

    public virtual ICollection<APISESWAGGERManipulation> APISESWAGGERManipulations { get; set; } = new List<APISESWAGGERManipulation>();

    public virtual ICollection<APISESubmissionKeyValuePair> APISESubmissionKeyValuePairs { get; set; } = new List<APISESubmissionKeyValuePair>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<APISECollection> APISECollections { get; set; } = new List<APISECollection>();
}