// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class APISECollectionSWAGGERSKeyValue
{
    public Guid Id { get; set; }

    public Guid APISECollectionId { get; set; }

    public Guid APISESwaggerId { get; set; }

    public string KeyPair { get; set; }

    public string KeyType { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public Guid KeyGroupId { get; set; }

    public virtual APISECollection APISECollection { get; set; }

    public virtual APISESWAGGER APISESwagger { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}