// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AspNetUser
{
    public string Id { get; set; }

    public string UserName { get; set; }

    public string NormalizedUserName { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string ConcurrencyStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public DateTimeOffset? LockoutEnd { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public virtual ICollection<AIReportRequest> AIReportRequests { get; set; } = new List<AIReportRequest>();

    public virtual ICollection<APISECollectionSWAGGERSKeyValue> APISECollectionSWAGGERSKeyValues { get; set; } = new List<APISECollectionSWAGGERSKeyValue>();

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigCreatedBies { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigUSERs { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<APISESWAGGERManipulation> APISESWAGGERManipulations { get; set; } = new List<APISESWAGGERManipulation>();

    public virtual ICollection<APISESWAGGER> APISESWAGGERs { get; set; } = new List<APISESWAGGER>();

    public virtual ICollection<ApplicationEventLog> ApplicationEventLogs { get; set; } = new List<ApplicationEventLog>();

    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; } = new List<AspNetUserClaim>();

    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; } = new List<AspNetUserLogin>();

    public virtual ICollection<AspNetUserToken> AspNetUserTokens { get; set; } = new List<AspNetUserToken>();

    public virtual ICollection<AssetPurchaseOrder> AssetPurchaseOrderCreatedBies { get; set; } = new List<AssetPurchaseOrder>();

    public virtual ICollection<AssetPurchaseOrderItem> AssetPurchaseOrderItems { get; set; } = new List<AssetPurchaseOrderItem>();

    public virtual ICollection<AssetPurchaseOrder> AssetPurchaseOrderPurchaseOrderApprovedBies { get; set; } = new List<AssetPurchaseOrder>();

    public virtual ICollection<AssetPurchaseOrderTransaction> AssetPurchaseOrderTransactions { get; set; } = new List<AssetPurchaseOrderTransaction>();

    public virtual ICollection<AssetRegisterCategory> AssetRegisterCategories { get; set; } = new List<AssetRegisterCategory>();

    public virtual ICollection<AssetRegisterComment> AssetRegisterComments { get; set; } = new List<AssetRegisterComment>();

    public virtual ICollection<AssetRegister> AssetRegisterCreatedBies { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssetRegisterDepreciationSceduleItem> AssetRegisterDepreciationSceduleItems { get; set; } = new List<AssetRegisterDepreciationSceduleItem>();

    public virtual ICollection<AssetRegisterDepreciationScheduleDisposalCode> AssetRegisterDepreciationScheduleDisposalCodes { get; set; } = new List<AssetRegisterDepreciationScheduleDisposalCode>();

    public virtual ICollection<AssetRegisterDepreciationSchedule> AssetRegisterDepreciationSchedules { get; set; } = new List<AssetRegisterDepreciationSchedule>();

    public virtual ICollection<AssetRegisterInspectionScheduleComment> AssetRegisterInspectionScheduleComments { get; set; } = new List<AssetRegisterInspectionScheduleComment>();

    public virtual ICollection<AssetRegisterInspectionSchedule> AssetRegisterInspectionSchedules { get; set; } = new List<AssetRegisterInspectionSchedule>();

    public virtual ICollection<AssetRegisterIssuesLog> AssetRegisterIssuesLogs { get; set; } = new List<AssetRegisterIssuesLog>();

    public virtual ICollection<AssetRegisterMaintenanceLog> AssetRegisterMaintenanceLogAllocatedTos { get; set; } = new List<AssetRegisterMaintenanceLog>();

    public virtual ICollection<AssetRegisterMaintenanceLogComment> AssetRegisterMaintenanceLogComments { get; set; } = new List<AssetRegisterMaintenanceLogComment>();

    public virtual ICollection<AssetRegisterMaintenanceLog> AssetRegisterMaintenanceLogCreatedBies { get; set; } = new List<AssetRegisterMaintenanceLog>();

    public virtual ICollection<AssetRegisterMaintenanceLogType> AssetRegisterMaintenanceLogTypes { get; set; } = new List<AssetRegisterMaintenanceLogType>();

    public virtual ICollection<AssetRegister> AssetRegisterOwnedBies { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssetRegisterReservationComment> AssetRegisterReservationComments { get; set; } = new List<AssetRegisterReservationComment>();

    public virtual ICollection<AssetRegisterReservation> AssetRegisterReservationCreatedBies { get; set; } = new List<AssetRegisterReservation>();

    public virtual ICollection<AssetRegisterReservationReport> AssetRegisterReservationReports { get; set; } = new List<AssetRegisterReservationReport>();

    public virtual ICollection<AssetRegisterReservation> AssetRegisterReservationRequestedBies { get; set; } = new List<AssetRegisterReservation>();

    public virtual ICollection<AssetRegisterReservationTermsAndCondition> AssetRegisterReservationTermsAndConditions { get; set; } = new List<AssetRegisterReservationTermsAndCondition>();

    public virtual ICollection<AssetRegisterWarranty> AssetRegisterWarranties { get; set; } = new List<AssetRegisterWarranty>();

    public virtual ICollection<AssetSupplierComment> AssetSupplierComments { get; set; } = new List<AssetSupplierComment>();

    public virtual ICollection<AssetSupplierContact> AssetSupplierContacts { get; set; } = new List<AssetSupplierContact>();

    public virtual ICollection<AssetSupplier> AssetSuppliers { get; set; } = new List<AssetSupplier>();

    public virtual ICollection<AssuranceAutomatedControlTestDefinition> AssuranceAutomatedControlTestDefinitions { get; set; } = new List<AssuranceAutomatedControlTestDefinition>();

    public virtual ICollection<AssuranceAutomatedControlTestExecutedOutcome> AssuranceAutomatedControlTestExecutedOutcomes { get; set; } = new List<AssuranceAutomatedControlTestExecutedOutcome>();

    public virtual ICollection<AssuranceProgram> AssuranceProgramCreatedBies { get; set; } = new List<AssuranceProgram>();

    public virtual ICollection<AssuranceProgram> AssuranceProgramOwners { get; set; } = new List<AssuranceProgram>();

    public virtual ICollection<AssuranceSchedule> AssuranceScheduleCreatedBies { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSchedule> AssuranceScheduleOwners { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceScheduleUser> AssuranceScheduleUserCreatedBies { get; set; } = new List<AssuranceScheduleUser>();

    public virtual ICollection<AssuranceScheduleUser> AssuranceScheduleUserUsers { get; set; } = new List<AssuranceScheduleUser>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLogs { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceSubmissionProcessedComment> AssuranceSubmissionProcessedComments { get; set; } = new List<AssuranceSubmissionProcessedComment>();

    public virtual ICollection<AssuranceSubmissionProcessed> AssuranceSubmissionProcesseds { get; set; } = new List<AssuranceSubmissionProcessed>();

    public virtual ICollection<AssuranceTemplate> AssuranceTemplateCreatedBies { get; set; } = new List<AssuranceTemplate>();

    public virtual ICollection<AssuranceTemplate> AssuranceTemplateOwners { get; set; } = new List<AssuranceTemplate>();

    public virtual ICollection<AssuranceTemplatesScoringBand> AssuranceTemplatesScoringBands { get; set; } = new List<AssuranceTemplatesScoringBand>();

    public virtual ICollection<AssuranceVoiceTestTemplate> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplate>();

    public virtual ICollection<BCPLibrary> BCPLibraryCreatedBies { get; set; } = new List<BCPLibrary>();

    public virtual ICollection<BCPLibrary> BCPLibraryOwners { get; set; } = new List<BCPLibrary>();

    public virtual ICollection<BusinessContinuityPlan> BusinessContinuityPlanCreatedBies { get; set; } = new List<BusinessContinuityPlan>();

    public virtual ICollection<BusinessContinuityPlan> BusinessContinuityPlanOwners { get; set; } = new List<BusinessContinuityPlan>();

    public virtual ICollection<BusinessContinuityPlansComment> BusinessContinuityPlansComments { get; set; } = new List<BusinessContinuityPlansComment>();

    public virtual ICollection<ComplaintsOrCompliment> ComplaintsOrComplimentCreatedBies { get; set; } = new List<ComplaintsOrCompliment>();

    public virtual ICollection<ComplaintsOrCompliment> ComplaintsOrComplimentOwners { get; set; } = new List<ComplaintsOrCompliment>();

    public virtual ICollection<ComplaintsOrComplimentsComment> ComplaintsOrComplimentsComments { get; set; } = new List<ComplaintsOrComplimentsComment>();

    public virtual ICollection<CredScraperGoverningBody> CredScraperGoverningBodies { get; set; } = new List<CredScraperGoverningBody>();

    public virtual ICollection<CredScraperUserRecord> CredScraperUserRecordCreatedBies { get; set; } = new List<CredScraperUserRecord>();

    public virtual ICollection<CredScraperUserRecord> CredScraperUserRecordReportsToUsers { get; set; } = new List<CredScraperUserRecord>();

    public virtual ICollection<Credential> CredentialCreatdBies { get; set; } = new List<Credential>();

    public virtual ICollection<Credential> CredentialGovernanceOwners { get; set; } = new List<Credential>();

    public virtual ICollection<Credential> CredentialOwners { get; set; } = new List<Credential>();

    public virtual ICollection<CredentialsCondition> CredentialsConditions { get; set; } = new List<CredentialsCondition>();

    public virtual ICollection<CredentialsConditionsPeriodicAcknowledgement> CredentialsConditionsPeriodicAcknowledgementAcknowledgementBies { get; set; } = new List<CredentialsConditionsPeriodicAcknowledgement>();

    public virtual ICollection<CredentialsConditionsPeriodicAcknowledgement> CredentialsConditionsPeriodicAcknowledgementCreatedBies { get; set; } = new List<CredentialsConditionsPeriodicAcknowledgement>();

    public virtual ICollection<CredentialsNotation> CredentialsNotations { get; set; } = new List<CredentialsNotation>();

    public virtual ICollection<CredentialsRegulatoryBody> CredentialsRegulatoryBodies { get; set; } = new List<CredentialsRegulatoryBody>();

    public virtual ICollection<CredentialsReprimand> CredentialsReprimands { get; set; } = new List<CredentialsReprimand>();

    public virtual ICollection<CredentialsUndertaking> CredentialsUndertakings { get; set; } = new List<CredentialsUndertaking>();

    public virtual ICollection<CredentialsUserRegistration> CredentialsUserRegistrationCreatedBies { get; set; } = new List<CredentialsUserRegistration>();

    public virtual ICollection<CredentialsUserRegistration> CredentialsUserRegistrationLineManagerUsers { get; set; } = new List<CredentialsUserRegistration>();

    public virtual ICollection<CredentialsUserRegistration> CredentialsUserRegistrationUsers { get; set; } = new List<CredentialsUserRegistration>();

    public virtual ICollection<Division> Divisions { get; set; } = new List<Division>();

    public virtual ICollection<Doc> DocCreatedBies { get; set; } = new List<Doc>();

    public virtual ICollection<Doc> DocOwners { get; set; } = new List<Doc>();

    public virtual ICollection<DocsAccessLog> DocsAccessLogs { get; set; } = new List<DocsAccessLog>();

    public virtual ICollection<DocsDelegatedAuthority> DocsDelegatedAuthorityCreatedBies { get; set; } = new List<DocsDelegatedAuthority>();

    public virtual ICollection<DocsDelegatedAuthority> DocsDelegatedAuthorityUsers { get; set; } = new List<DocsDelegatedAuthority>();

    public virtual ICollection<DocsItemComment> DocsItemComments { get; set; } = new List<DocsItemComment>();

    public virtual ICollection<DocsItem> DocsItemCreatedBies { get; set; } = new List<DocsItem>();

    public virtual ICollection<DocsItem> DocsItemOwners { get; set; } = new List<DocsItem>();

    public virtual ICollection<DocsItemsExemption> DocsItemsExemptionCreatedBies { get; set; } = new List<DocsItemsExemption>();

    public virtual ICollection<DocsItemsExemption> DocsItemsExemptionDecisionUsers { get; set; } = new List<DocsItemsExemption>();

    public virtual ICollection<DocsItemsExemption> DocsItemsExemptionRequestingUsers { get; set; } = new List<DocsItemsExemption>();

    public virtual ICollection<DocsKnowledgeTransferUser> DocsKnowledgeTransferUserCreatedBies { get; set; } = new List<DocsKnowledgeTransferUser>();

    public virtual ICollection<DocsKnowledgeTransferUser> DocsKnowledgeTransferUserUsers { get; set; } = new List<DocsKnowledgeTransferUser>();

    public virtual ICollection<DocsKnowledgeTransfer> DocsKnowledgeTransfers { get; set; } = new List<DocsKnowledgeTransfer>();

    public virtual ICollection<DocsLibraryItemsExemptionsCondition> DocsLibraryItemsExemptionsConditionAcceptedByUsers { get; set; } = new List<DocsLibraryItemsExemptionsCondition>();

    public virtual ICollection<DocsLibraryItemsExemptionsCondition> DocsLibraryItemsExemptionsConditionCreatedBies { get; set; } = new List<DocsLibraryItemsExemptionsCondition>();

    public virtual ICollection<DocsRelatedChildArtifact> DocsRelatedChildArtifacts { get; set; } = new List<DocsRelatedChildArtifact>();

    public virtual ICollection<DocsReview> DocsReviewCreatedBies { get; set; } = new List<DocsReview>();

    public virtual ICollection<DocsReview> DocsReviewOwners { get; set; } = new List<DocsReview>();

    public virtual ICollection<DocsSubscriptionUser> DocsSubscriptionUserCreatedBies { get; set; } = new List<DocsSubscriptionUser>();

    public virtual ICollection<DocsSubscriptionUser> DocsSubscriptionUserUsers { get; set; } = new List<DocsSubscriptionUser>();

    public virtual ICollection<DocstensExemptionsComment> DocstensExemptionsComments { get; set; } = new List<DocstensExemptionsComment>();

    public virtual ICollection<Improvement> ImprovementCreatedBies { get; set; } = new List<Improvement>();

    public virtual ICollection<Improvement> ImprovementOwners { get; set; } = new List<Improvement>();

    public virtual ICollection<ImprovementTeamMember> ImprovementTeamMemberCreatedBies { get; set; } = new List<ImprovementTeamMember>();

    public virtual ICollection<ImprovementTeamMember> ImprovementTeamMemberUsers { get; set; } = new List<ImprovementTeamMember>();

    public virtual ICollection<ImprovementTool> ImprovementTools { get; set; } = new List<ImprovementTool>();

    public virtual ICollection<ImprovementType> ImprovementTypes { get; set; } = new List<ImprovementType>();

    public virtual ICollection<ImprovementsDelivered> ImprovementsDelivereds { get; set; } = new List<ImprovementsDelivered>();

    public virtual ICollection<ImprovementsObjective> ImprovementsObjectiveCreatedBies { get; set; } = new List<ImprovementsObjective>();

    public virtual ICollection<ImprovementsObjective> ImprovementsObjectiveOwners { get; set; } = new List<ImprovementsObjective>();

    public virtual ICollection<Incident> IncidentCreatedBies { get; set; } = new List<Incident>();

    public virtual ICollection<Incident> IncidentOwners { get; set; } = new List<Incident>();

    public virtual ICollection<Incident> IncidentReportingUsers { get; set; } = new List<Incident>();

    public virtual ICollection<IncidentsCannedBCP> IncidentsCannedBCPs { get; set; } = new List<IncidentsCannedBCP>();

    public virtual ICollection<IncidentsCannedReport> IncidentsCannedReports { get; set; } = new List<IncidentsCannedReport>();

    public virtual ICollection<IncidentsCategory> IncidentsCategories { get; set; } = new List<IncidentsCategory>();

    public virtual ICollection<IncidentsDivisionOwner> IncidentsDivisionOwnerCreatedBies { get; set; } = new List<IncidentsDivisionOwner>();

    public virtual ICollection<IncidentsDivisionOwner> IncidentsDivisionOwnerUsers { get; set; } = new List<IncidentsDivisionOwner>();

    public virtual ICollection<IncidentsEmergencyResponseType> IncidentsEmergencyResponseTypes { get; set; } = new List<IncidentsEmergencyResponseType>();

    public virtual ICollection<IncidentsEmergencyResponse> IncidentsEmergencyResponses { get; set; } = new List<IncidentsEmergencyResponse>();

    public virtual ICollection<IncidentsExternalTeamMember> IncidentsExternalTeamMembers { get; set; } = new List<IncidentsExternalTeamMember>();

    public virtual ICollection<IncidentsFieldInvestigationCategoriesAndForm> IncidentsFieldInvestigationCategoriesAndForms { get; set; } = new List<IncidentsFieldInvestigationCategoriesAndForm>();

    public virtual ICollection<IncidentsFieldInvestigation> IncidentsFieldInvestigationCreatedBies { get; set; } = new List<IncidentsFieldInvestigation>();

    public virtual ICollection<IncidentsFieldInvestigation> IncidentsFieldInvestigationOwners { get; set; } = new List<IncidentsFieldInvestigation>();

    public virtual ICollection<IncidentsFieldInvestigationSubmissionLog> IncidentsFieldInvestigationSubmissionLogs { get; set; } = new List<IncidentsFieldInvestigationSubmissionLog>();

    public virtual ICollection<IncidentsInternalTeamMember> IncidentsInternalTeamMemberCreatedBies { get; set; } = new List<IncidentsInternalTeamMember>();

    public virtual ICollection<IncidentsInternalTeamMember> IncidentsInternalTeamMemberUsers { get; set; } = new List<IncidentsInternalTeamMember>();

    public virtual ICollection<IncidentsLessonsLearntKeyword> IncidentsLessonsLearntKeywords { get; set; } = new List<IncidentsLessonsLearntKeyword>();

    public virtual ICollection<IncidentsLessonsLearnt> IncidentsLessonsLearnts { get; set; } = new List<IncidentsLessonsLearnt>();

    public virtual ICollection<IncidentsRPOLibrary> IncidentsRPOLibraries { get; set; } = new List<IncidentsRPOLibrary>();

    public virtual ICollection<IncidentsRTOLibrary> IncidentsRTOLibraries { get; set; } = new List<IncidentsRTOLibrary>();

    public virtual ICollection<IncidentsRTOLibraryLinkIncident> IncidentsRTOLibraryLinkIncidentCommentBies { get; set; } = new List<IncidentsRTOLibraryLinkIncident>();

    public virtual ICollection<IncidentsRTOLibraryLinkIncident> IncidentsRTOLibraryLinkIncidentCreatedBies { get; set; } = new List<IncidentsRTOLibraryLinkIncident>();

    public virtual ICollection<IncidentsReport> IncidentsReports { get; set; } = new List<IncidentsReport>();

    public virtual ICollection<IncidentsReportsComment> IncidentsReportsComments { get; set; } = new List<IncidentsReportsComment>();

    public virtual ICollection<IncidentsSeverity> IncidentsSeverities { get; set; } = new List<IncidentsSeverity>();

    public virtual ICollection<IncidentsSnapChartCausalFactor> IncidentsSnapChartCausalFactors { get; set; } = new List<IncidentsSnapChartCausalFactor>();

    public virtual ICollection<IncidentsSnapChartLog> IncidentsSnapChartLogs { get; set; } = new List<IncidentsSnapChartLog>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementsOfNeedCreatedBies { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementsOfNeedOwners { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual ICollection<InternalAudit> InternalAuditBusinessUnitCommentsBies { get; set; } = new List<InternalAudit>();

    public virtual ICollection<InternalAudit> InternalAuditCreatedBies { get; set; } = new List<InternalAudit>();

    public virtual ICollection<InternalAudit> InternalAuditOwners { get; set; } = new List<InternalAudit>();

    public virtual ICollection<InternalAuditPlan> InternalAuditPlanCreatedBies { get; set; } = new List<InternalAuditPlan>();

    public virtual ICollection<InternalAuditPlan> InternalAuditPlanOwners { get; set; } = new List<InternalAuditPlan>();

    public virtual ICollection<InternalAuditPlanResource> InternalAuditPlanResourceCreatedBies { get; set; } = new List<InternalAuditPlanResource>();

    public virtual ICollection<InternalAuditPlanResource> InternalAuditPlanResourceUsers { get; set; } = new List<InternalAuditPlanResource>();

    public virtual ICollection<InternalAuditResource> InternalAuditResourceCreatedBies { get; set; } = new List<InternalAuditResource>();

    public virtual ICollection<InternalAuditResource> InternalAuditResourceUsers { get; set; } = new List<InternalAuditResource>();

    public virtual ICollection<IssuesActionTaskType> IssuesActionTaskTypeBaseOwners { get; set; } = new List<IssuesActionTaskType>();

    public virtual ICollection<IssuesActionTaskType> IssuesActionTaskTypeCreatedBies { get; set; } = new List<IssuesActionTaskType>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTaskAllocatedTos { get; set; } = new List<IssuesActionsTask>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTaskCreatedBies { get; set; } = new List<IssuesActionsTask>();

    public virtual ICollection<IssuesActionsTasksComment> IssuesActionsTasksComments { get; set; } = new List<IssuesActionsTasksComment>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverrideCreatedBies { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverrideOwners { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();

    public virtual ICollection<IssuesActionsTasksUrgencyAndOffset> IssuesActionsTasksUrgencyAndOffsets { get; set; } = new List<IssuesActionsTasksUrgencyAndOffset>();

    public virtual ICollection<RegulatoryEngagementBody> RegulatoryEngagementBodies { get; set; } = new List<RegulatoryEngagementBody>();

    public virtual ICollection<RegulatoryEngagementBodyContact> RegulatoryEngagementBodyContacts { get; set; } = new List<RegulatoryEngagementBodyContact>();

    public virtual ICollection<RegulatoryEngagement> RegulatoryEngagementCreatedBies { get; set; } = new List<RegulatoryEngagement>();

    public virtual ICollection<RegulatoryEngagementEventLog> RegulatoryEngagementEventLogs { get; set; } = new List<RegulatoryEngagementEventLog>();

    public virtual ICollection<RegulatoryEngagement> RegulatoryEngagementOwners { get; set; } = new List<RegulatoryEngagement>();

    public virtual ICollection<RegulatoryEngagementResource> RegulatoryEngagementResourceCreatedBies { get; set; } = new List<RegulatoryEngagementResource>();

    public virtual ICollection<RegulatoryEngagementResource> RegulatoryEngagementResourceUsers { get; set; } = new List<RegulatoryEngagementResource>();

    public virtual ICollection<RegulatoryEngagementsOutcome> RegulatoryEngagementsOutcomes { get; set; } = new List<RegulatoryEngagementsOutcome>();

    public virtual ICollection<Risk> RiskCreatedBies { get; set; } = new List<Risk>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveryAccountableOwners { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryControlScopeDesignEffectiveness> RiskDiscoveryControlScopeDesignEffectivenesses { get; set; } = new List<RiskDiscoveryControlScopeDesignEffectiveness>();

    public virtual ICollection<RiskDiscoveryControlScopeOperatingEffectiveness> RiskDiscoveryControlScopeOperatingEffectivenesses { get; set; } = new List<RiskDiscoveryControlScopeOperatingEffectiveness>();

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScopes { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveryCretedBies { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryResource> RiskDiscoveryResourceCreatedBies { get; set; } = new List<RiskDiscoveryResource>();

    public virtual ICollection<RiskDiscoveryResource> RiskDiscoveryResourceUsers { get; set; } = new List<RiskDiscoveryResource>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopeCreatedBies { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RiskDiscoveryScopeInherentAndResidualAssessment> RiskDiscoveryScopeInherentAndResidualAssessments { get; set; } = new List<RiskDiscoveryScopeInherentAndResidualAssessment>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopeRiskOwners { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<Risk> RiskOwners { get; set; } = new List<Risk>();

    public virtual ICollection<RisksControl> RisksControlCreatedBies { get; set; } = new List<RisksControl>();

    public virtual ICollection<RisksControl> RisksControlOwners { get; set; } = new List<RisksControl>();

    public virtual ICollection<RisksControlSuggestionComment> RisksControlSuggestionComments { get; set; } = new List<RisksControlSuggestionComment>();

    public virtual ICollection<RisksControlSuggestion> RisksControlSuggestions { get; set; } = new List<RisksControlSuggestion>();

    public virtual ICollection<RisksMatirxsConcequenceLabel> RisksMatirxsConcequenceLabels { get; set; } = new List<RisksMatirxsConcequenceLabel>();

    public virtual ICollection<RisksMatirxsLikelihoodLabel> RisksMatirxsLikelihoodLabels { get; set; } = new List<RisksMatirxsLikelihoodLabel>();

    public virtual ICollection<RisksMatrix> RisksMatrices { get; set; } = new List<RisksMatrix>();

    public virtual ICollection<RisksMatrixLikelihoodConsequenceField> RisksMatrixLikelihoodConsequenceFields { get; set; } = new List<RisksMatrixLikelihoodConsequenceField>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatchExecutedOutcome> RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatchExecutedOutcome>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RisksOwnedRiskAutomatedControlTestBatches { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestDefinition> RisksOwnedRiskAutomatedControlTestDefinitions { get; set; } = new List<RisksOwnedRiskAutomatedControlTestDefinition>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRiskCreatedBies { get; set; } = new List<RisksOwnedRisk>();

    public virtual ICollection<RisksOwnedRiskInherentAndRedisualAssessment> RisksOwnedRiskInherentAndRedisualAssessments { get; set; } = new List<RisksOwnedRiskInherentAndRedisualAssessment>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness> RisksOwnedRiskInherentAndResidualAssessmentControlEffectivenesses { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentUser> RisksOwnedRiskInherentAndResidualAssessmentUserCreatedBies { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentUser>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentUser> RisksOwnedRiskInherentAndResidualAssessmentUserUsers { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentUser>();

    public virtual ICollection<RisksOwnedRiskInherentResidualRiskAnalysis> RisksOwnedRiskInherentResidualRiskAnalyses { get; set; } = new List<RisksOwnedRiskInherentResidualRiskAnalysis>();

    public virtual ICollection<RisksOwnedRiskInherentRiskAnalysis> RisksOwnedRiskInherentRiskAnalyses { get; set; } = new List<RisksOwnedRiskInherentRiskAnalysis>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRiskOwners { get; set; } = new List<RisksOwnedRisk>();

    public virtual ICollection<RisksOwnedRiskResidualRiskAnalysis> RisksOwnedRiskResidualRiskAnalyses { get; set; } = new List<RisksOwnedRiskResidualRiskAnalysis>();

    public virtual ICollection<RisksStandardsAct> RisksStandardsActs { get; set; } = new List<RisksStandardsAct>();

    public virtual ICollection<RisksSuggestionComment> RisksSuggestionComments { get; set; } = new List<RisksSuggestionComment>();

    public virtual ICollection<RisksSuggestion> RisksSuggestionCreatedBies { get; set; } = new List<RisksSuggestion>();

    public virtual ICollection<RisksSuggestion> RisksSuggestionOwners { get; set; } = new List<RisksSuggestion>();

    public virtual ICollection<AspNetRole> Roles { get; set; } = new List<AspNetRole>();
}