// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetRegisterMaintenanceLogType
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssetRegisterMaintenanceLog> AssetRegisterMaintenanceLogs { get; set; } = new List<AssetRegisterMaintenanceLog>();

    public virtual AspNetUser CreatedBy { get; set; }
}