// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetRegisterReservation
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public Guid AssetRegisterReservationTermsAndConditionsId { get; set; }

    public string DisplayId { get; set; }

    public DateTime RequestedDt { get; set; }

    public string RequestedById { get; set; }

    public DateTime PlannedReturnDt { get; set; }

    public string IntendedUseDescription { get; set; }

    public DateTime? ReturnedDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual ICollection<AssetRegisterIssuesLog> AssetRegisterIssuesLogs { get; set; } = new List<AssetRegisterIssuesLog>();

    public virtual ICollection<AssetRegisterReservationComment> AssetRegisterReservationComments { get; set; } = new List<AssetRegisterReservationComment>();

    public virtual ICollection<AssetRegisterReservationReport> AssetRegisterReservationReports { get; set; } = new List<AssetRegisterReservationReport>();

    public virtual AssetRegisterReservationTermsAndCondition AssetRegisterReservationTermsAndConditions { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser RequestedBy { get; set; }
}