// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetRegister
{
    public Guid Id { get; set; }

    public Guid AssetSupplierId { get; set; }

    public Guid? AssetPurchaseOrderId { get; set; }

    public Guid AssetCategoryId { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid PrimaryLocationId { get; set; }

    public string LocationDetails { get; set; }

    public string OwnedById { get; set; }

    public DateTime RegistrationDate { get; set; }

    public DateTime DepreciationDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegisterCategory AssetCategory { get; set; }

    public virtual AssetPurchaseOrder AssetPurchaseOrder { get; set; }

    public virtual ICollection<AssetRegisterComment> AssetRegisterComments { get; set; } = new List<AssetRegisterComment>();

    public virtual ICollection<AssetRegisterDepreciationSchedule> AssetRegisterDepreciationSchedules { get; set; } = new List<AssetRegisterDepreciationSchedule>();

    public virtual ICollection<AssetRegisterInspectionSchedule> AssetRegisterInspectionSchedules { get; set; } = new List<AssetRegisterInspectionSchedule>();

    public virtual ICollection<AssetRegisterIssuesLog> AssetRegisterIssuesLogs { get; set; } = new List<AssetRegisterIssuesLog>();

    public virtual ICollection<AssetRegisterMaintenanceLog> AssetRegisterMaintenanceLogs { get; set; } = new List<AssetRegisterMaintenanceLog>();

    public virtual ICollection<AssetRegisterReservationTermsAndCondition> AssetRegisterReservationTermsAndConditions { get; set; } = new List<AssetRegisterReservationTermsAndCondition>();

    public virtual ICollection<AssetRegisterReservation> AssetRegisterReservations { get; set; } = new List<AssetRegisterReservation>();

    public virtual ICollection<AssetRegisterWarranty> AssetRegisterWarranties { get; set; } = new List<AssetRegisterWarranty>();

    public virtual AssetSupplier AssetSupplier { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser OwnedBy { get; set; }

    public virtual Division PrimaryLocation { get; set; }
}