// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetRegisterReservationReport
{
    public Guid Id { get; set; }

    public Guid AssetRegisterReservationId { get; set; }

    public string DisplayId { get; set; }

    public int OnLoanOnReturn { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegisterReservation AssetRegisterReservation { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}