// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetRegisterMaintenanceLog
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public Guid? AssetRegisterIssuesLogId { get; set; }

    public Guid AssetRegisterMaintenanceLogTypeId { get; set; }

    public string AllocatedToId { get; set; }

    public DateTime RequestedDt { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? CompletedDt { get; set; }

    public string Description { get; set; }

    public double? ComponentCosts { get; set; }

    public double? LaborCosts { get; set; }

    public double? TotalCosts { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public virtual AspNetUser AllocatedTo { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual AssetRegisterIssuesLog AssetRegisterIssuesLog { get; set; }

    public virtual ICollection<AssetRegisterMaintenanceLogComment> AssetRegisterMaintenanceLogComments { get; set; } = new List<AssetRegisterMaintenanceLogComment>();

    public virtual AssetRegisterMaintenanceLogType AssetRegisterMaintenanceLogType { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<IssuesActionsTask> IssueActionTasks { get; set; } = new List<IssuesActionsTask>();
}