// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetPurchaseOrderItem
{
    public Guid Id { get; set; }

    public Guid AssetPurchaseOrderId { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int Quantity { get; set; }

    public double UnitPrice { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetPurchaseOrder AssetPurchaseOrder { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}