// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetPurchaseOrderTransaction
{
    public Guid Id { get; set; }

    public Guid AssetPurchaseOrderId { get; set; }

    public string DisplayId { get; set; }

    public string DebitCredit { get; set; }

    public double Amount { get; set; }

    public string Currency { get; set; }

    public string TaxCode { get; set; }

    public double TaxAmount { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetPurchaseOrder AssetPurchaseOrder { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}