// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetSupplier
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Web { get; set; }

    public string KeyWords { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public Guid AssetSupplierTypeId { get; set; }

    public virtual ICollection<AssetPurchaseOrder> AssetPurchaseOrders { get; set; } = new List<AssetPurchaseOrder>();

    public virtual ICollection<AssetRegister> AssetRegisters { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssetSupplierComment> AssetSupplierComments { get; set; } = new List<AssetSupplierComment>();

    public virtual ICollection<AssetSupplierContact> AssetSupplierContacts { get; set; } = new List<AssetSupplierContact>();

    public virtual AssetSupplierType AssetSupplierType { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}