// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetPurchaseOrder
{
    public Guid Id { get; set; }

    public Guid AssetSupplierId { get; set; }

    public string DisplayId { get; set; }

    public string SupplierOrderReference { get; set; }

    public DateTime PurchaseDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double Amount { get; set; }

    public string Currency { get; set; }

    public string TaxCode { get; set; }

    public double TaxAmount { get; set; }

    public string PurchaseOrderApprovedById { get; set; }

    public DateTime? PurchaseOrderApprovalDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssetPurchaseOrderItem> AssetPurchaseOrderItems { get; set; } = new List<AssetPurchaseOrderItem>();

    public virtual ICollection<AssetPurchaseOrderTransaction> AssetPurchaseOrderTransactions { get; set; } = new List<AssetPurchaseOrderTransaction>();

    public virtual ICollection<AssetRegister> AssetRegisters { get; set; } = new List<AssetRegister>();

    public virtual AssetSupplier AssetSupplier { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser PurchaseOrderApprovedBy { get; set; }
}