// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssetSupplierContact
{
    public Guid Id { get; set; }

    public Guid AssetSupplierId { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Role { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetSupplier AssetSupplier { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}