// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceTemplate
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceProgramId { get; set; }

    public string Name { get; set; }

    public string TemplateJSON { get; set; }

    public string OwnerId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreaetdDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigs { get; set; } = new List<APISECollectionTestConfig>();

    public virtual AssuranceProgram AssuranceProgram { get; set; }

    public virtual ICollection<AssuranceSchedule> AssuranceSchedules { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLogs { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceSubmissionProcessed> AssuranceSubmissionProcesseds { get; set; } = new List<AssuranceSubmissionProcessed>();

    public virtual ICollection<AssuranceTemplatesScoringBand> AssuranceTemplatesScoringBands { get; set; } = new List<AssuranceTemplatesScoringBand>();

    public virtual ICollection<AssuranceVoiceTestTemplate> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplate>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser Owner { get; set; }
}