// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceSubmissionProcessed
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public Guid AssuranceSubmissionLogId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public double ContributionScore { get; set; }

    public double ContributionMaxScore { get; set; }

    public double ContributionPercentage { get; set; }

    public string ScoringBandName { get; set; }

    public string ScoringBandBGColor { get; set; }

    public string ScoringBandFGColor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssuranceSubmissionProcessedComment> AssuranceSubmissionProcessedComments { get; set; } = new List<AssuranceSubmissionProcessedComment>();

    public virtual ICollection<AssuranceSubmissionProcessedGrouping> AssuranceSubmissionProcessedGroupings { get; set; } = new List<AssuranceSubmissionProcessedGrouping>();

    public virtual ICollection<AssuranceSubmissionProcessedResponsesStructured> AssuranceSubmissionProcessedResponsesStructureds { get; set; } = new List<AssuranceSubmissionProcessedResponsesStructured>();

    public virtual ICollection<AssuranceSubmissionProcessedResponsesUnStructured> AssuranceSubmissionProcessedResponsesUnStructureds { get; set; } = new List<AssuranceSubmissionProcessedResponsesUnStructured>();

    public virtual ICollection<AssuranceSubmissionProcessedRisksStandardsActsWeighting> AssuranceSubmissionProcessedRisksStandardsActsWeightings { get; set; } = new List<AssuranceSubmissionProcessedRisksStandardsActsWeighting>();

    public virtual ICollection<AssuranceSubmissionProcessedVoiceTranscriptionAndSentiment> AssuranceSubmissionProcessedVoiceTranscriptionAndSentiments { get; set; } = new List<AssuranceSubmissionProcessedVoiceTranscriptionAndSentiment>();

    public virtual AssuranceTemplate AssuranceTemplate { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }
}