// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceSubmissionProcessedGrouping
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceSubmissionProcessedId { get; set; }

    public string GroupName { get; set; }

    public int GroupOrder { get; set; }

    public int QuestionOrderId { get; set; }

    public virtual AssuranceSubmissionProcessed AssuranceSubmissionProcessed { get; set; }
}