// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceAutomatedControlTestBatchRun
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceAutomatedControlTestDefinitionId { get; set; }

    public int RunNumber { get; set; }

    public DateTime RunStartDT { get; set; }

    public DateTime? RunEndDT { get; set; }

    public int TestsPassed { get; set; }

    public int TestsFailed { get; set; }

    public int IssuesRaised { get; set; }

    public virtual AssuranceAutomatedControlTestDefinition AssuranceAutomatedControlTestDefinition { get; set; }

    public virtual ICollection<AssuranceAutomatedControlTestExecutedOutcome> AssuranceAutomatedControlTestExecutedOutcomes { get; set; } = new List<AssuranceAutomatedControlTestExecutedOutcome>();

    public virtual ICollection<IssuesActionsTask> IssueActionTasks { get; set; } = new List<IssuesActionsTask>();
}