// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceSubmissionProcessedComment
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceSubmissionProcessedId { get; set; }

    public string UserId { get; set; }

    public string Comment { get; set; }

    public DateTime TimeStamp { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public bool? SentimentIsPositive { get; set; }

    public double? SentimentConfidence { get; set; }

    public virtual AssuranceSubmissionProcessed AssuranceSubmissionProcessed { get; set; }

    public virtual AspNetUser CreatedByNavigation { get; set; }
}