// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceVoiceTestTemplate
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceScheduleId { get; set; }

    public Guid AssuranceProgramId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public Guid DivisionId { get; set; }

    public string TestJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssuranceProgram AssuranceProgram { get; set; }

    public virtual AssuranceSchedule AssuranceSchedule { get; set; }

    public virtual AssuranceTemplate AssuranceTemplate { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }
}