// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceSubmissionProcessedRisksStandardsActsWeighting
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceSubmissionprocessedId { get; set; }

    public int QuestionorderId { get; set; }

    public string QuestionIdentifier { get; set; }

    public string QuestionText { get; set; }

    public string Answer { get; set; }

    public string Indicator { get; set; }

    public Guid RisksStandardsActsId { get; set; }

    public double Weighting { get; set; }

    public virtual AssuranceSubmissionProcessed AssuranceSubmissionprocessed { get; set; }

    public virtual RisksStandardsAct RisksStandardsActs { get; set; }
}