// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceAutomatedControlTestDefinition
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceScheduleId { get; set; }

    public int AutomatedControlTestTypeId { get; set; }

    public int Threshold { get; set; }

    public string TextJSON { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public int BatchSize { get; set; }

    public virtual ICollection<AssuranceAutomatedControlTestBatchRun> AssuranceAutomatedControlTestBatchRuns { get; set; } = new List<AssuranceAutomatedControlTestBatchRun>();

    public virtual AssuranceSchedule AssuranceSchedule { get; set; }

    public virtual AspNetUser CreatedByNavigation { get; set; }
}