// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceSchedule
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceProgramId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public string OwnerId { get; set; }

    public Guid DivisionId { get; set; }

    public DateTime StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public int Frequency { get; set; }

    public string FrequencySettings { get; set; }

    public int AutoCleanup { get; set; }

    public int? IncompleteAuditExpiry { get; set; }

    public int IncludeQuotas { get; set; }

    public int? QuotaQuantity { get; set; }

    public int? QuotaTotal { get; set; }

    public int SetReminders { get; set; }

    public int? OwnerCommencementReminder { get; set; }

    public int? OwnerCompletionReminder { get; set; }

    public int? CollectorCommencementReminder { get; set; }

    public int? CollectorCompletionReminder { get; set; }

    public int EnableSelfSubscribe { get; set; }

    public int EnableExternalAccess { get; set; }

    public int ScheduleEnabled { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public int ExternalAccessReload { get; set; }

    public int? FilteredDivisions { get; set; }

    public string DivisionsFilter { get; set; }

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigs { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<AssuranceAutomatedControlTestDefinition> AssuranceAutomatedControlTestDefinitions { get; set; } = new List<AssuranceAutomatedControlTestDefinition>();

    public virtual AssuranceProgram AssuranceProgram { get; set; }

    public virtual ICollection<AssuranceScheduleUser> AssuranceScheduleUsers { get; set; } = new List<AssuranceScheduleUser>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLogs { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual AssuranceTemplate AssuranceTemplate { get; set; }

    public virtual ICollection<AssuranceVoiceTestTemplate> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplate>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();
}