// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceVoiceStaging
{
    public Guid Id { get; set; }

    public string AudioFile { get; set; }

    public string JSONData { get; set; }

    public Guid? TranscriptionId { get; set; }

    public string TranscriptionURL { get; set; }

    public int Status { get; set; }

    public DateTime CreatedDt { get; set; }
}