// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceSubmissionProcessedResponsesStructured
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceSubmissionProcessedId { get; set; }

    public int QuestionOrderId { get; set; }

    public string QuestionIdentifier { get; set; }

    public string QuestionText { get; set; }

    public double ContributionScoreSum { get; set; }

    public double ContributionScoreMax { get; set; }

    public int IsNA { get; set; }

    public int IsIneffectiveControl { get; set; }

    public int IsNonResponse { get; set; }

    public int IsNotAsked { get; set; }

    public virtual AssuranceSubmissionProcessed AssuranceSubmissionProcessed { get; set; }

    public virtual ICollection<AssuranceSubmissionprocessedResponsesStructuredAnswer> AssuranceSubmissionprocessedResponsesStructuredAnswers { get; set; } = new List<AssuranceSubmissionprocessedResponsesStructuredAnswer>();
}