// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceTemplatesScoringBand
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public string Name { get; set; }

    public double LowerBand { get; set; }

    public double UpperBand { get; set; }

    public string BGColor { get; set; }

    public string FGColor { get; set; }

    public int AutoFailOverride { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssuranceTemplate AssuranceTemplate { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }
}