// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class AssuranceProgram
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreateedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssuranceSchedule> AssuranceSchedules { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLogs { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceTemplate> AssuranceTemplates { get; set; } = new List<AssuranceTemplate>();

    public virtual ICollection<AssuranceVoiceTestTemplate> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplate>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser Owner { get; set; }
}