// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Attachment
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string RefTable { get; set; }

    public Guid RefTableId { get; set; }

    public string BlobUri { get; set; }

    public string FileName { get; set; }

    public string FileExtension { get; set; }

    public string FileAnnotation { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }
}