// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class BusinessContinuityPlan
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid? IncidentId { get; set; }

    public Guid BCPLibraryId { get; set; }

    public DateTime StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string BCPJSON { get; set; }

    public double CompletionPercentage { get; set; }

    public string OwnerId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual BCPLibrary BCPLibrary { get; set; }

    public virtual ICollection<BusinessContinuityPlansComment> BusinessContinuityPlansComments { get; set; } = new List<BusinessContinuityPlansComment>();

    public virtual ICollection<BusinessContinuityPlansLinkActionTask> BusinessContinuityPlansLinkActionTasks { get; set; } = new List<BusinessContinuityPlansLinkActionTask>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<IssuesActionsTask> IssueActionTasks { get; set; } = new List<IssuesActionsTask>();
}