// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class BusinessContinuityPlansLinkActionTask
{
    public Guid BusinessContinuityPlanId { get; set; }

    public Guid IssuesActionsTasksActionId { get; set; }

    public Guid IssuesActionsTasksTaskId { get; set; }

    public virtual BusinessContinuityPlan BusinessContinuityPlan { get; set; }

    public virtual IssuesActionsTask IssuesActionsTasksAction { get; set; }

    public virtual IssuesActionsTask IssuesActionsTasksTask { get; set; }
}