// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class ComplaintsOrCompliment
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public int Type { get; set; }

    public string Contact { get; set; }

    public string ContactAddress { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string Commentary { get; set; }

    public string OwnerId { get; set; }

    public string InitialResponse { get; set; }

    public int? Priority { get; set; }

    public DateTime? ResolutionRequiredDt { get; set; }

    public DateTime? ResolutionDt { get; set; }

    public string Outcome { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<ComplaintsOrComplimentsComment> ComplaintsOrComplimentsComments { get; set; } = new List<ComplaintsOrComplimentsComment>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}