// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class CredScraperUserRecord
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid GoverningBodyId { get; set; }

    public string RegistrationId { get; set; }

    public string ReportsToUserId { get; set; }

    public string LastScrapeFile { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual CredScraperGoverningBody GoverningBody { get; set; }

    public virtual AspNetUser ReportsToUser { get; set; }
}