// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class CredentialsCondition
{
    public Guid Id { get; set; }

    public Guid CredentialsId { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime ConditionEffectiveDate { get; set; }

    public DateTime? ConditionCompletionDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Credential Credentials { get; set; }

    public virtual ICollection<CredentialsConditionsPeriodicAcknowledgement> CredentialsConditionsPeriodicAcknowledgements { get; set; } = new List<CredentialsConditionsPeriodicAcknowledgement>();
}