// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Credential
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string GovernanceOwnerId { get; set; }

    public Guid? ParentId { get; set; }

    public string Name { get; set; }

    public string RegistrationNumber { get; set; }

    public string GrantingBody { get; set; }

    public string CredentialStatus { get; set; }

    public DateTime DateOfObtainment { get; set; }

    public DateTime? DateOfExpiry { get; set; }

    public string PrinciplePlaceOfProfession { get; set; }

    public string PrincilePlaceOfProfessionAddress { get; set; }

    public string CreatdById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatdBy { get; set; }

    public virtual ICollection<CredentialsCondition> CredentialsConditions { get; set; } = new List<CredentialsCondition>();

    public virtual ICollection<CredentialsNotation> CredentialsNotations { get; set; } = new List<CredentialsNotation>();

    public virtual ICollection<CredentialsReprimand> CredentialsReprimands { get; set; } = new List<CredentialsReprimand>();

    public virtual ICollection<CredentialsUndertaking> CredentialsUndertakings { get; set; } = new List<CredentialsUndertaking>();

    public virtual AspNetUser GovernanceOwner { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}