// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Division
{
    public Guid Id { get; set; }

    public Guid? ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigs { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<AssetRegister> AssetRegisters { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssuranceSchedule> AssuranceSchedules { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLogs { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceSubmissionProcessed> AssuranceSubmissionProcesseds { get; set; } = new List<AssuranceSubmissionProcessed>();

    public virtual ICollection<AssuranceVoiceTestTemplate> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplate>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<IncidentsDivisionOwner> IncidentsDivisionOwners { get; set; } = new List<IncidentsDivisionOwner>();

    public virtual ICollection<InternalAuditPlan> InternalAuditPlans { get; set; } = new List<InternalAuditPlan>();

    public virtual ICollection<InternalAudit> InternalAudits { get; set; } = new List<InternalAudit>();

    public virtual ICollection<Division> InverseParent { get; set; } = new List<Division>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverrides { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();

    public virtual Division Parent { get; set; }

    public virtual ICollection<RegulatoryEngagement> RegulatoryEngagements { get; set; } = new List<RegulatoryEngagement>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveries { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopes { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRisks { get; set; } = new List<RisksOwnedRisk>();
}