// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Doc
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string DisplayPath { get; set; }

    public int ItemType { get; set; }

    public string Name { get; set; }

    public Guid? ParentId { get; set; }

    public int AccessLevel { get; set; }

    public string OwnerId { get; set; }

    public string Description { get; set; }

    public string KeyWords { get; set; }

    public string RecommendedFor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<DocsAccessLog> DocsAccessLogs { get; set; } = new List<DocsAccessLog>();

    public virtual ICollection<DocsDelegatedAuthority> DocsDelegatedAuthorities { get; set; } = new List<DocsDelegatedAuthority>();

    public virtual ICollection<DocsItem> DocsItems { get; set; } = new List<DocsItem>();

    public virtual ICollection<DocsKnowledgeTransfer> DocsKnowledgeTransfers { get; set; } = new List<DocsKnowledgeTransfer>();

    public virtual ICollection<DocsRelatedChildArtifact> DocsRelatedChildArtifacts { get; set; } = new List<DocsRelatedChildArtifact>();

    public virtual ICollection<DocsReview> DocsReviews { get; set; } = new List<DocsReview>();

    public virtual ICollection<DocsSubscriptionUser> DocsSubscriptionUsers { get; set; } = new List<DocsSubscriptionUser>();

    public virtual ICollection<Doc> InverseParent { get; set; } = new List<Doc>();

    public virtual AspNetUser Owner { get; set; }

    public virtual Doc Parent { get; set; }

    public virtual ICollection<Risk> Risks { get; set; } = new List<Risk>();
}