// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsLibraryItemsExemptionsCondition
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsItemsExemptionId { get; set; }

    public string Condution { get; set; }

    public int? AcceptanceStatus { get; set; }

    public string AcceptedByUserId { get; set; }

    public DateTime? AcceptedDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser AcceptedByUser { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual DocsItemsExemption DocsItemsExemption { get; set; }
}