// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsReview
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public Guid DocsItemId { get; set; }

    public string OwnerId { get; set; }

    public DateTime ReviewDt { get; set; }

    public DateTime? ReviewCompletedDt { get; set; }

    public DateTime? NextRevewDt { get; set; }

    public string ReviewCommentary { get; set; }

    public string ReviewOutcome { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Doc Docs { get; set; }

    public virtual DocsItem DocsItem { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}