// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsItemsExemption
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsItemId { get; set; }

    public string ExemptionRequest { get; set; }

    public string RequestingUserId { get; set; }

    public string ExemptionDecision { get; set; }

    public int? ExemptionDecisionStatus { get; set; }

    public DateTime? DecisionDt { get; set; }

    public string DecisionUserId { get; set; }

    public DateTime RequestedEffectiveDate { get; set; }

    public DateTime? RequestedExpiryDate { get; set; }

    public DateTime? ExemptionEffectiveDate { get; set; }

    public DateTime? ExemptionExpiryDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime Createddt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser DecisionUser { get; set; }

    public virtual DocsItem DocsItem { get; set; }

    public virtual ICollection<DocsLibraryItemsExemptionsCondition> DocsLibraryItemsExemptionsConditions { get; set; } = new List<DocsLibraryItemsExemptionsCondition>();

    public virtual ICollection<DocstensExemptionsComment> DocstensExemptionsComments { get; set; } = new List<DocstensExemptionsComment>();

    public virtual AspNetUser RequestingUser { get; set; }
}