// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsKnowledgeTransferUser
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsKnowledgeTransferId { get; set; }

    public string UserId { get; set; }

    public DateTime RequestDate { get; set; }

    public DateTime? AcknowledgementDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual DocsKnowledgeTransfer DocsKnowledgeTransfer { get; set; }

    public virtual AspNetUser User { get; set; }
}