// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsItem
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public string OwnerId { get; set; }

    public string Version { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ReleaseNotes { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreaedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Doc Docs { get; set; }

    public virtual ICollection<DocsItemComment> DocsItemComments { get; set; } = new List<DocsItemComment>();

    public virtual ICollection<DocsItemsExemption> DocsItemsExemptions { get; set; } = new List<DocsItemsExemption>();

    public virtual ICollection<DocsKnowledgeTransfer> DocsKnowledgeTransfers { get; set; } = new List<DocsKnowledgeTransfer>();

    public virtual ICollection<DocsRelatedChildArtifact> DocsRelatedChildArtifacts { get; set; } = new List<DocsRelatedChildArtifact>();

    public virtual ICollection<DocsReview> DocsReviews { get; set; } = new List<DocsReview>();

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}