// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsKnowledgeTransfer
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public Guid DocsItemId { get; set; }

    public bool IncludeDelegates { get; set; }

    public bool IncludeSubscribers { get; set; }

    public string ReadReceiptStatement { get; set; }

    public DateTime RequestDt { get; set; }

    public DateTime RequiredDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Doc Docs { get; set; }

    public virtual DocsItem DocsItem { get; set; }

    public virtual ICollection<DocsKnowledgeTransferUser> DocsKnowledgeTransferUsers { get; set; } = new List<DocsKnowledgeTransferUser>();
}