// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class DocsAccessLog
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public string Action { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Doc Docs { get; set; }
}