// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class ENUMReference
{
    public Guid Id { get; set; }

    public string TableName { get; set; }

    public string ColumnName { get; set; }

    public int EnumId { get; set; }

    public string EnumValue { get; set; }
}