// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Improvement
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public Guid DivisionId { get; set; }

    public int Priority { get; set; }

    public DateTime RequiredCompletionDate { get; set; }

    public int PDSAPhaseStatus { get; set; }

    public int ImprovementStatus { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid ImprovementTypeId { get; set; }

    public string StrategyDescription { get; set; }

    public string CalculatedQualitative { get; set; }

    public string CalulatedQuantitative { get; set; }

    public string SubmittedQualitative { get; set; }

    public string SubmittedQuantitative { get; set; }

    public string DeliveredImprovementDescription { get; set; }

    public string FollowUpActionsRequried { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string KeyWords { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual ICollection<ImprovementTeamMember> ImprovementTeamMembers { get; set; } = new List<ImprovementTeamMember>();

    public virtual ImprovementType ImprovementType { get; set; }

    public virtual ICollection<ImprovementsDelivered> ImprovementsDelivereds { get; set; } = new List<ImprovementsDelivered>();

    public virtual ICollection<ImprovementsObjective> ImprovementsObjectives { get; set; } = new List<ImprovementsObjective>();

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<AssuranceSchedule> AssuranceSchedules { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<ComplaintsOrCompliment> ComplaintOrCompliments { get; set; } = new List<ComplaintsOrCompliment>();

    public virtual ICollection<Improvement> ImprovementChildren { get; set; } = new List<Improvement>();

    public virtual ICollection<Improvement> ImprovementParents { get; set; } = new List<Improvement>();

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveries { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RisksOwnedRiskInherentAndRedisualAssessment> RiskOwnedRiskInherentAndResidualRiskAssessments { get; set; } = new List<RisksOwnedRiskInherentAndRedisualAssessment>();

    public virtual ICollection<RisksStandardsAct> RisksStandardsActs { get; set; } = new List<RisksStandardsAct>();
}