// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsReport
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentId { get; set; }

    public Guid IncidentCannedReportsId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Incident Incident { get; set; }

    public virtual IncidentsCannedReport IncidentCannedReports { get; set; }

    public virtual ICollection<IncidentsReportsComment> IncidentsReportsComments { get; set; } = new List<IncidentsReportsComment>();
}