// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Incident
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public string ReportingUserId { get; set; }

    public int IncidentTypeId { get; set; }

    public Guid? IncidentCategoryId { get; set; }

    public Guid? IncidentSeverityId { get; set; }

    public string ContactPerson { get; set; }

    public string ContactDetails { get; set; }

    public DateTime ReportedDt { get; set; }

    public string Description { get; set; }

    public string MaximumReasonableOutcome { get; set; }

    public int? MROAssessment { get; set; }

    public string MROOverride { get; set; }

    public int EmergencyResponseCalled { get; set; }

    public string OwnerId { get; set; }

    public string ImmediateActionsTaken { get; set; }

    public string SummaryInvolved { get; set; }

    public string SummaryResultedIn { get; set; }

    public string SummaryMayHaveResultedIn { get; set; }

    public string SummaryResponseSummary { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public DateTime? CompletedDt { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual IncidentsCategory IncidentCategory { get; set; }

    public virtual IncidentsSeverity IncidentSeverity { get; set; }

    public virtual ICollection<IncidentsEmergencyResponse> IncidentsEmergencyResponses { get; set; } = new List<IncidentsEmergencyResponse>();

    public virtual ICollection<IncidentsExternalTeamMember> IncidentsExternalTeamMembers { get; set; } = new List<IncidentsExternalTeamMember>();

    public virtual ICollection<IncidentsFieldInvestigation> IncidentsFieldInvestigations { get; set; } = new List<IncidentsFieldInvestigation>();

    public virtual ICollection<IncidentsInternalTeamMember> IncidentsInternalTeamMembers { get; set; } = new List<IncidentsInternalTeamMember>();

    public virtual ICollection<IncidentsLessonsLearnt> IncidentsLessonsLearnts { get; set; } = new List<IncidentsLessonsLearnt>();

    public virtual ICollection<IncidentsRPOLibraryLinkIncident> IncidentsRPOLibraryLinkIncidents { get; set; } = new List<IncidentsRPOLibraryLinkIncident>();

    public virtual ICollection<IncidentsRTOLibraryLinkIncident> IncidentsRTOLibraryLinkIncidents { get; set; } = new List<IncidentsRTOLibraryLinkIncident>();

    public virtual ICollection<IncidentsReport> IncidentsReports { get; set; } = new List<IncidentsReport>();

    public virtual ICollection<IncidentsSnapChartCausalFactor> IncidentsSnapChartCausalFactors { get; set; } = new List<IncidentsSnapChartCausalFactor>();

    public virtual ICollection<IncidentsSnapChartLog> IncidentsSnapChartLogs { get; set; } = new List<IncidentsSnapChartLog>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementsOfNeeds { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual AspNetUser Owner { get; set; }

    public virtual AspNetUser ReportingUser { get; set; }

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();

    public virtual ICollection<Incident> IncidentChildren { get; set; } = new List<Incident>();

    public virtual ICollection<Incident> IncidentParents { get; set; } = new List<Incident>();

    public virtual ICollection<IncidentsInternalTeamMember> IncidentsFieldInvestigationInternalTeamMembers { get; set; } = new List<IncidentsInternalTeamMember>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RiskOwnedRiskAutomatedControlTestBatches { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();

    public virtual ICollection<Risk> Risks { get; set; } = new List<Risk>();
}