// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsReportsComment
{
    public Guid Id { get; set; }

    public Guid IncidentReportId { get; set; }

    public string Comment { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual IncidentsReport IncidentReport { get; set; }
}