// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsEmergencyResponseType
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ContactInstructions { get; set; }

    public string ContactPhone { get; set; }

    public string ContactEmail { get; set; }

    public string ContactWeb { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<IncidentsEmergencyResponse> IncidentsEmergencyResponses { get; set; } = new List<IncidentsEmergencyResponse>();
}