// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsFieldInvestigationExternalPartiesLinkIncident
{
    public Guid IncidentsFieldInvestigationsExternalPartiesId { get; set; }

    public Guid IncidentId { get; set; }

    public virtual IncidentsExternalTeamMember IncidentsFieldInvestigationsExternalParties { get; set; }
}