// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsFieldInvestigationsFormResult
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentsFieldInvestigationId { get; set; }

    public Guid IncidentsFieldInvestigationSubmissionLogId { get; set; }

    public string QuestionKey { get; set; }

    public string QuestionText { get; set; }

    public int SortOrder { get; set; }

    public string QuestionType { get; set; }

    public string QuestionOptions { get; set; }

    public string Response { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreqatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual IncidentsFieldInvestigation IncidentsFieldInvestigation { get; set; }
}