// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsSeverity
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<IncidentsCannedBCP> IncidentsCannedBCPs { get; set; } = new List<IncidentsCannedBCP>();

    public virtual ICollection<IncidentsCannedReport> IncidentsCannedReports { get; set; } = new List<IncidentsCannedReport>();

    public virtual ICollection<IncidentsDivisionOwner> IncidentsDivisionOwners { get; set; } = new List<IncidentsDivisionOwner>();

    public virtual ICollection<IncidentsRPOLibrary> IncidentsRPOLibraries { get; set; } = new List<IncidentsRPOLibrary>();

    public virtual ICollection<IncidentsRTOLibrary> IncidentsRTOLibraries { get; set; } = new List<IncidentsRTOLibrary>();

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScopes { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RisksControl> RisksControls { get; set; } = new List<RisksControl>();
}