// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsRPOLibraryLinkIncident
{
    public Guid IncidentRPOLibraryId { get; set; }

    public Guid IncidentId { get; set; }

    public string RPOComment { get; set; }

    public string RPOCommentBy { get; set; }

    public int? RPOAchieved { get; set; }

    public string RPOCreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual Incident Incident { get; set; }

    public virtual IncidentsRPOLibrary IncidentRPOLibrary { get; set; }
}