// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsDivisionOwner
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public string UserId { get; set; }

    public int IncidentTypeId { get; set; }

    public Guid IncidentCategoryId { get; set; }

    public Guid IncidentSeverityId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual IncidentsCategory IncidentCategory { get; set; }

    public virtual IncidentsSeverity IncidentSeverity { get; set; }

    public virtual AspNetUser User { get; set; }
}