// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsLessonsLearntKeyword
{
    public Guid Id { get; set; }

    public Guid IncidentLessonsLearntId { get; set; }

    public string Keyword { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual IncidentsLessonsLearnt IncidentLessonsLearnt { get; set; }
}