// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsExternalTeamMember
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentId { get; set; }

    public string Name { get; set; }

    public string OrganisationName { get; set; }

    public string Alias { get; set; }

    public string Role { get; set; }

    public string RelationshipToIncident { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Incident Incident { get; set; }

    public virtual ICollection<IncidentsFieldInvestigationExternalPartiesLinkIncident> IncidentsFieldInvestigationExternalPartiesLinkIncidents { get; set; } = new List<IncidentsFieldInvestigationExternalPartiesLinkIncident>();
}