// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsFieldInvestigation
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentId { get; set; }

    public string OwnerId { get; set; }

    public Guid IncidentFieldIvestigationCategoryAndFormId { get; set; }

    public string FieldInvestigationFormJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Incident Incident { get; set; }

    public virtual IncidentsFieldInvestigationCategoriesAndForm IncidentFieldIvestigationCategoryAndForm { get; set; }

    public virtual ICollection<IncidentsFieldInvestigationSubmissionLog> IncidentsFieldInvestigationSubmissionLogs { get; set; } = new List<IncidentsFieldInvestigationSubmissionLog>();

    public virtual AspNetUser Owner { get; set; }
}