// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IncidentsFieldInvestigationCategoriesAndForm
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public int TypeId { get; set; }

    public Guid ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string FormJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CratedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<IncidentsFieldInvestigationSubmissionLog> IncidentsFieldInvestigationSubmissionLogs { get; set; } = new List<IncidentsFieldInvestigationSubmissionLog>();

    public virtual ICollection<IncidentsFieldInvestigation> IncidentsFieldInvestigations { get; set; } = new List<IncidentsFieldInvestigation>();
}