// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class InternalAuditResource
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid InternalAuditId { get; set; }

    public string UserId { get; set; }

    public string RoleInAudit { get; set; }

    public double AllocatedPercentage { get; set; }

    public DateTime StartDt { get; set; }

    public DateTime EndDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual InternalAudit InternalAudit { get; set; }

    public virtual AspNetUser User { get; set; }
}