// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IssuesActionsTasksComment
{
    public Guid id { get; set; }

    public Guid IATID { get; set; }

    public string Comment { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public bool Enabled { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual IssuesActionsTask IAT { get; set; }
}