// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IssuesActionTaskType
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public bool SystemType { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public bool Enabled { get; set; }

    public string BaseOwnerId { get; set; }

    public string DisplayId { get; set; }

    public virtual AspNetUser BaseOwner { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverrides { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();
}