// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class IssuesActionsTask
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string AllocatedToId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Guid IATTypeId { get; set; }

    public DateTime DueDate { get; set; }

    public string Outcome { get; set; }

    public int IATCategory { get; set; }

    public string Contact { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public Guid DivisionId { get; set; }

    public Guid? UrgencyId { get; set; }

    public virtual AspNetUser AllocatedTo { get; set; }

    public virtual ICollection<BusinessContinuityPlansLinkActionTask> BusinessContinuityPlansLinkActionTaskIssuesActionsTasksActions { get; set; } = new List<BusinessContinuityPlansLinkActionTask>();

    public virtual ICollection<BusinessContinuityPlansLinkActionTask> BusinessContinuityPlansLinkActionTaskIssuesActionsTasksTasks { get; set; } = new List<BusinessContinuityPlansLinkActionTask>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual IssuesActionTaskType IATType { get; set; }

    public virtual ICollection<IssuesActionsTasksComment> IssuesActionsTasksComments { get; set; } = new List<IssuesActionsTasksComment>();

    public virtual ICollection<IssuesActionsTasksLinkToSelf> IssuesActionsTasksLinkToSelves { get; set; } = new List<IssuesActionsTasksLinkToSelf>();

    public virtual IssuesActionsTasksUrgencyAndOffset Urgency { get; set; }

    public virtual ICollection<AssetRegisterMaintenanceLog> AssetRegisterMaintenanceLogs { get; set; } = new List<AssetRegisterMaintenanceLog>();

    public virtual ICollection<AssuranceAutomatedControlTestBatchRun> AssuranceAutomatedControlTestBatchRuns { get; set; } = new List<AssuranceAutomatedControlTestBatchRun>();

    public virtual ICollection<BusinessContinuityPlan> BusinessContinuityPlans { get; set; } = new List<BusinessContinuityPlan>();

    public virtual ICollection<ComplaintsOrCompliment> ComplaintsOrCompliments { get; set; } = new List<ComplaintsOrCompliment>();

    public virtual ICollection<Credential> Credentials { get; set; } = new List<Credential>();

    public virtual ICollection<DocsItem> DocsItems { get; set; } = new List<DocsItem>();

    public virtual ICollection<DocsReview> DocsReviews { get; set; } = new List<DocsReview>();

    public virtual ICollection<ImprovementsObjective> ImprovementObjectives { get; set; } = new List<ImprovementsObjective>();

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementOfNeeds { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual ICollection<InternalAudit> InternalAudits { get; set; } = new List<InternalAudit>();

    public virtual ICollection<RegulatoryEngagementsOutcome> RegulatoryEngagementOutcomes { get; set; } = new List<RegulatoryEngagementsOutcome>();

    public virtual ICollection<RiskDiscoveryScopeInherentAndResidualAssessment> RiskDescoveryScopeInherentAndResidualAssessments { get; set; } = new List<RiskDiscoveryScopeInherentAndResidualAssessment>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveries { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryControlScopeOperatingEffectiveness> RiskDiscoveryContorlScopeOperatingEffectivenesses { get; set; } = new List<RiskDiscoveryControlScopeOperatingEffectiveness>();

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScopes { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RiskDiscoveryControlScopeDesignEffectiveness> RiskDiscoveryScopeDesignEffectivenesses { get; set; } = new List<RiskDiscoveryControlScopeDesignEffectiveness>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopes { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RiskOwnedRiskAutomatedControlTestBatches { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();
}