// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Key
{
    public string Id { get; set; }

    public int Version { get; set; }

    public DateTime Created { get; set; }

    public string Use { get; set; }

    public string Algorithm { get; set; }

    public bool IsX509Certificate { get; set; }

    public bool DataProtected { get; set; }

    public string Data { get; set; }
}