// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RegulatoryEngagementResource
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RegulatoryEngagementId { get; set; }

    public string UserId { get; set; }

    public string RoleInEngagement { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RegulatoryEngagement RegulatoryEngagement { get; set; }

    public virtual AspNetUser User { get; set; }
}