// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RegulatoryEngagementsOutcome
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RegulatoryEngagementId { get; set; }

    public Guid Category { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime EffectiveDt { get; set; }

    public DateTime ExpiryDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RegulatoryEngagement RegulatoryEngagement { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}