// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RegulatoryEngagementBodyContact
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RegulatoryEngagementBodyId { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string EngagementTypes { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RegulatoryEngagementBody RegulatoryEngagementBody { get; set; }

    public virtual ICollection<RegulatoryEngagement> RegulatoryEngagements { get; set; } = new List<RegulatoryEngagement>();
}