// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RiskDiscoveryControlScopeOperatingEffectiveness
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskDiscoveryControlScopeDesignEffectivenessId { get; set; }

    public int OESampleType { get; set; }

    public string OESampleDescription { get; set; }

    public int OESampleSize { get; set; }

    public int OEEffectivenessThreshold { get; set; }

    public int TestsPassed { get; set; }

    public int TestsFailed { get; set; }

    public int IssuesRaised { get; set; }

    public int IncidentsRaised { get; set; }

    public string OperatingEffectivenessSummary { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RiskDiscoveryControlScopeDesignEffectiveness RiskDiscoveryControlScopeDesignEffectiveness { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}