// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksOwnedRisk
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public Guid RiskId { get; set; }

    public string OwnerId { get; set; }

    public DateTime EffectiveDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual Risk Risk { get; set; }

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopes { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestDefinition> RisksOwnedRiskAutomatedControlTestDefinitions { get; set; } = new List<RisksOwnedRiskAutomatedControlTestDefinition>();

    public virtual ICollection<RisksOwnedRiskInherentAndRedisualAssessment> RisksOwnedRiskInherentAndRedisualAssessments { get; set; } = new List<RisksOwnedRiskInherentAndRedisualAssessment>();
}