// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RiskDiscoveryScope
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskDiscoveryId { get; set; }

    public string DefinitionASA { get; set; }

    public string DefinitionItMay { get; set; }

    public string DefinitionResultingIn { get; set; }

    public int ExistingRisk { get; set; }

    public Guid? RiskId { get; set; }

    public int? ExistingOwnedRisk { get; set; }

    public Guid? RisksOwnedRiskId { get; set; }

    public Guid? DivisionId { get; set; }

    public string RiskOwnerId { get; set; }

    public string RiskSuitabilityComments { get; set; }

    public int RiskControlsEmbedded { get; set; }

    public string RiskControlsComments { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual Risk Risk { get; set; }

    public virtual RiskDiscovery RiskDiscovery { get; set; }

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScopes { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual AspNetUser RiskOwner { get; set; }

    public virtual RisksOwnedRisk RisksOwnedRisk { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}