// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RiskDiscoveryScopeInherentAndResidualAssessment
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskDiscoveryScopeId { get; set; }

    public string ReveiwHistory { get; set; }

    public string InherentRiskAssessmentQuality { get; set; }

    public string ResidualRiskAssessmentQuality { get; set; }

    public int ControlsDETested { get; set; }

    public int ControlsOETested { get; set; }

    public int? SignOffComplete { get; set; }

    public int? SignOffAppropriate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RiskDiscoveryControlScope RiskDiscoveryScope { get; set; }

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}