// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RiskDiscoveryControlScopeDesignEffectiveness
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskDiscoveryControlScopeId { get; set; }

    public string AssuranceStatement { get; set; }

    public Guid? AssuranceProgramId { get; set; }

    public Guid? AssuranceTemplateId { get; set; }

    public string AssuranceCoverage { get; set; }

    public int AutomatedControlTest { get; set; }

    public int AutomatedControlBatchType { get; set; }

    public string AutomatedControlBatchDetails { get; set; }

    public int TestsCompelteness { get; set; }

    public int TestsAuthorisation { get; set; }

    public int TestsRemedialCorrection { get; set; }

    public int TestsSegregationOfDuties { get; set; }

    public int ControlMitigatesRisk { get; set; }

    public string FinalControlCommentary { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RiskDiscoveryControlScope RiskDiscoveryControlScope { get; set; }

    public virtual ICollection<RiskDiscoveryControlScopeOperatingEffectiveness> RiskDiscoveryControlScopeOperatingEffectivenesses { get; set; } = new List<RiskDiscoveryControlScopeOperatingEffectiveness>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}