// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class Risk
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskMatrixId { get; set; }

    public Guid? RiskSuggestionId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string AsA { get; set; }

    public string ItMay { get; set; }

    public string ResultingIn { get; set; }

    public string RATLikelihood { get; set; }

    public string RATConsequence { get; set; }

    public string RATImpact { get; set; }

    public string RATBGColor { get; set; }

    public string RATFGColor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopes { get; set; } = new List<RiskDiscoveryScope>();

    public virtual RisksMatrix RiskMatrix { get; set; }

    public virtual RisksSuggestion RiskSuggestion { get; set; }

    public virtual ICollection<RisksControlSuggestion> RisksControlSuggestions { get; set; } = new List<RisksControlSuggestion>();

    public virtual ICollection<RisksControl> RisksControls { get; set; } = new List<RisksControl>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRisks { get; set; } = new List<RisksOwnedRisk>();

    public virtual ICollection<Doc> Docs { get; set; } = new List<Doc>();

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();

    public virtual ICollection<RisksStandardsAct> RisksStandardsActs { get; set; } = new List<RisksStandardsAct>();
}