// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksSuggestion
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string Title { get; set; }

    public string AsA { get; set; }

    public string ItMay { get; set; }

    public string ResultingIn { get; set; }

    public string ScenarioResponse { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual ICollection<Risk> Risks { get; set; } = new List<Risk>();

    public virtual ICollection<RisksSuggestionComment> RisksSuggestionComments { get; set; } = new List<RisksSuggestionComment>();

    public virtual ICollection<RisksStandardsAct> RiskStandardActs { get; set; } = new List<RisksStandardsAct>();
}