// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksMatrix
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int LikelihoodScale { get; set; }

    public int ConsequenceScale { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<Risk> Risks { get; set; } = new List<Risk>();

    public virtual ICollection<RisksMatirxsConcequenceLabel> RisksMatirxsConcequenceLabels { get; set; } = new List<RisksMatirxsConcequenceLabel>();

    public virtual ICollection<RisksMatirxsLikelihoodLabel> RisksMatirxsLikelihoodLabels { get; set; } = new List<RisksMatirxsLikelihoodLabel>();

    public virtual ICollection<RisksMatrixLikelihoodConsequenceField> RisksMatrixLikelihoodConsequenceFields { get; set; } = new List<RisksMatrixLikelihoodConsequenceField>();
}