// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RiskDiscovery
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public string AccountableOwnerId { get; set; }

    public string AccountableOwnerComments { get; set; }

    public string BusinessUnit { get; set; }

    public string BusinessUnitFunction { get; set; }

    public int PoliciesIdentified { get; set; }

    public string PolicyComments { get; set; }

    public int ProcessesIdentified { get; set; }

    public string ProcessesComments { get; set; }

    public int WorkInstructionsIdentified { get; set; }

    public string WorkInstructionsComments { get; set; }

    public int PolicyExemptionsIdentified { get; set; }

    public string PolicyExemptionsComments { get; set; }

    public string RiskCultureStatement { get; set; }

    public string WhatIsRisk { get; set; }

    public string WhatAreYourRisks { get; set; }

    public string CretedById { get; set; }

    public DateTime CreeatdDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser AccountableOwner { get; set; }

    public virtual AspNetUser CretedBy { get; set; }

    public virtual Division Division { get; set; }

    public virtual ICollection<RiskDiscoveryResource> RiskDiscoveryResources { get; set; } = new List<RiskDiscoveryResource>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopes { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();

    public virtual ICollection<IssuesActionsTask> IssuesActionsTasks { get; set; } = new List<IssuesActionsTask>();
}