// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksMatrixLikelihoodConsequenceField
{
    public Guid RiskMatrixId { get; set; }

    public Guid RiskMatrixConsequenceId { get; set; }

    public Guid RiskMatrixLikelihoodId { get; set; }

    public string DisplayId { get; set; }

    public string BGColor { get; set; }

    public string FGColor { get; set; }

    public string Label { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RisksMatrix RiskMatrix { get; set; }

    public virtual RisksMatirxsConcequenceLabel RiskMatrixConsequence { get; set; }

    public virtual RisksMatirxsLikelihoodLabel RiskMatrixLikelihood { get; set; }
}