// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksControl
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid? RiskControlSuggestionId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string ControlRationale { get; set; }

    public string Description { get; set; }

    public string Completeness { get; set; }

    public string Authority { get; set; }

    public string RemedialCorrection { get; set; }

    public string SegregationOfDuties { get; set; }

    public string RemediatesRiskBy { get; set; }

    public string FailureAppetiate { get; set; }

    public string EscalationPath { get; set; }

    public int AutomaticallyRaiseIncident { get; set; }

    public Guid? IncidentCategoryId { get; set; }

    public Guid? IncidentSeverityId { get; set; }

    public int? IncidentTypeId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string IncidentMRO { get; set; }

    public Guid? RIskId { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual IncidentsCategory IncidentCategory { get; set; }

    public virtual IncidentsSeverity IncidentSeverity { get; set; }

    public virtual AspNetUser Owner { get; set; }

    public virtual Risk RIsk { get; set; }

    public virtual RisksControlSuggestion RiskControlSuggestion { get; set; }

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScopes { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestDefinition> RisksOwnedRiskAutomatedControlTestDefinitions { get; set; } = new List<RisksOwnedRiskAutomatedControlTestDefinition>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness> RisksOwnedRiskInherentAndResidualAssessmentControlEffectivenesses { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness>();
}