// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksStandardsAct
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid? ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssuranceSubmissionProcessedRisksStandardsActsWeighting> AssuranceSubmissionProcessedRisksStandardsActsWeightings { get; set; } = new List<AssuranceSubmissionProcessedRisksStandardsActsWeighting>();

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual ICollection<RisksStandardsAct> InverseParent { get; set; } = new List<RisksStandardsAct>();

    public virtual RisksStandardsAct Parent { get; set; }

    public virtual ICollection<Improvement> Improvements { get; set; } = new List<Improvement>();

    public virtual ICollection<InternalAudit> InternalAudits { get; set; } = new List<InternalAudit>();

    public virtual ICollection<RisksSuggestion> RiskSuggestions { get; set; } = new List<RisksSuggestion>();

    public virtual ICollection<Risk> Risks { get; set; } = new List<Risk>();
}