// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksOwnedRiskAutomatedControlTestBatchExecutedOutcome
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskOwnedRiskAutomatedControlTestBatchId { get; set; }

    public int BatchNumber { get; set; }

    public int QuestionOrderId { get; set; }

    public string QuestionIdentifier { get; set; }

    public string QuestionText { get; set; }

    public string Answer { get; set; }

    public string TestType { get; set; }

    public string TestValues { get; set; }

    public int TestOutcome { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual RisksOwnedRiskAutomatedControlTestBatch RiskOwnedRiskAutomatedControlTestBatch { get; set; }
}