// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class RisksControlSuggestion
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskId { get; set; }

    public string MyRole { get; set; }

    public string ProblemObserved { get; set; }

    public string CompletenessSuggestion { get; set; }

    public string AuthoritySuggestion { get; set; }

    public string RemedialCorrectionSuggestion { get; set; }

    public string SegregationOfDutiesSuggestion { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUser CreatedBy { get; set; }

    public virtual Risk Risk { get; set; }

    public virtual ICollection<RisksControlSuggestionComment> RisksControlSuggestionComments { get; set; } = new List<RisksControlSuggestionComment>();

    public virtual ICollection<RisksControl> RisksControls { get; set; } = new List<RisksControl>();
}