// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class SSRSReportList
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid ReportGroupId { get; set; }

    public string ReportName { get; set; }

    public string ReportURL { get; set; }

    public int Status { get; set; }

    public virtual SSRSReportGroup ReportGroup { get; set; }
}