// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class SSRSReportGroup
{
    public Guid Id { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<SSRSReportList> SSRSReportLists { get; set; } = new List<SSRSReportList>();
}