// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSVParser.Data.Models;

public partial class TenantKey
{
    public string TenantId { get; set; }

    public string SearchServiceName { get; set; }

    public string SearchKey { get; set; }
}