// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class APISESubmissionKeyValuePairs
{
    public Guid Id { get; set; }

    public Guid APISESubmissionId { get; set; }

    public Guid SwaggerId { get; set; }

    public Guid CollectionId { get; set; }

    public string KeyPair { get; set; }

    public string ValuePair { get; set; }

    public virtual APISESubmission APISESubmission { get; set; }

    public virtual APISECollection Collection { get; set; }

    public virtual APISESWAGGERS Swagger { get; set; }
}