// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class APISESubmission
{
    public Guid Id { get; set; }

    public Guid SwaggerId { get; set; }

    public string CollectionIds { get; set; }

    public string Payload { get; set; }

    public DateTime CreatedDt { get; set; }

    public virtual ICollection<APISESubmissionKeyValuePairs> APISESubmissionKeyValuePairs { get; set; } = new List<APISESubmissionKeyValuePairs>();
}