// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class APISECollection
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public virtual ICollection<APISECollectionSWAGGERSKeyValue> APISECollectionSWAGGERSKeyValue { get; set; } = new List<APISECollectionSWAGGERSKeyValue>();

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfig { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<APISESubmissionKeyValuePairs> APISESubmissionKeyValuePairs { get; set; } = new List<APISESubmissionKeyValuePairs>();

    public virtual ICollection<APISESWAGGERS> APISESwagger { get; set; } = new List<APISESWAGGERS>();
}