// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class APISESWAGGERManipulations
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid APISESwaggerId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Manipulation { get; set; }

    public string Objective { get; set; }

    public string Target { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual APISESWAGGERS APISESwagger { get; set; }

    public virtual AspNetUsers CreatedByNavigation { get; set; }
}