// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class ApplicationEventLog
{
    public Guid Id { get; set; }

    public string TableName { get; set; }

    public int EventType { get; set; }

    public Guid RecordId { get; set; }

    public string JSONObjectType { get; set; }

    public string JSONObject { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }
}