// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AspNetUsers
{
    public string Id { get; set; }

    public string UserName { get; set; }

    public string NormalizedUserName { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string ConcurrencyStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public DateTimeOffset? LockoutEnd { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public virtual ICollection<AIReportRequest> AIReportRequest { get; set; } = new List<AIReportRequest>();

    public virtual ICollection<APISECollectionSWAGGERSKeyValue> APISECollectionSWAGGERSKeyValue { get; set; } = new List<APISECollectionSWAGGERSKeyValue>();

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigCreatedBy { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfigUSER { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<APISESWAGGERManipulations> APISESWAGGERManipulations { get; set; } = new List<APISESWAGGERManipulations>();

    public virtual ICollection<APISESWAGGERS> APISESWAGGERS { get; set; } = new List<APISESWAGGERS>();

    public virtual ICollection<ApplicationEventLog> ApplicationEventLog { get; set; } = new List<ApplicationEventLog>();

    public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; } = new List<AspNetUserClaims>();

    public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; } = new List<AspNetUserLogins>();

    public virtual ICollection<AspNetUserTokens> AspNetUserTokens { get; set; } = new List<AspNetUserTokens>();

    public virtual ICollection<AssetPurchaseOrderItems> AssetPurchaseOrderItems { get; set; } = new List<AssetPurchaseOrderItems>();

    public virtual ICollection<AssetPurchaseOrderTransactions> AssetPurchaseOrderTransactions { get; set; } = new List<AssetPurchaseOrderTransactions>();

    public virtual ICollection<AssetPurchaseOrders> AssetPurchaseOrdersCreatedBy { get; set; } = new List<AssetPurchaseOrders>();

    public virtual ICollection<AssetPurchaseOrders> AssetPurchaseOrdersPurchaseOrderApprovedBy { get; set; } = new List<AssetPurchaseOrders>();

    public virtual ICollection<AssetRegisterCategories> AssetRegisterCategories { get; set; } = new List<AssetRegisterCategories>();

    public virtual ICollection<AssetRegisterComments> AssetRegisterComments { get; set; } = new List<AssetRegisterComments>();

    public virtual ICollection<AssetRegister> AssetRegisterCreatedBy { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssetRegisterDepreciationSceduleItems> AssetRegisterDepreciationSceduleItems { get; set; } = new List<AssetRegisterDepreciationSceduleItems>();

    public virtual ICollection<AssetRegisterDepreciationSchedule> AssetRegisterDepreciationSchedule { get; set; } = new List<AssetRegisterDepreciationSchedule>();

    public virtual ICollection<AssetRegisterDepreciationScheduleDisposalCodes> AssetRegisterDepreciationScheduleDisposalCodes { get; set; } = new List<AssetRegisterDepreciationScheduleDisposalCodes>();

    public virtual ICollection<AssetRegisterInspectionScheduleComments> AssetRegisterInspectionScheduleComments { get; set; } = new List<AssetRegisterInspectionScheduleComments>();

    public virtual ICollection<AssetRegisterInspectionSchedules> AssetRegisterInspectionSchedules { get; set; } = new List<AssetRegisterInspectionSchedules>();

    public virtual ICollection<AssetRegisterIssuesLogs> AssetRegisterIssuesLogs { get; set; } = new List<AssetRegisterIssuesLogs>();

    public virtual ICollection<AssetRegisterMaintenanceLogComments> AssetRegisterMaintenanceLogComments { get; set; } = new List<AssetRegisterMaintenanceLogComments>();

    public virtual ICollection<AssetRegisterMaintenanceLogTypes> AssetRegisterMaintenanceLogTypes { get; set; } = new List<AssetRegisterMaintenanceLogTypes>();

    public virtual ICollection<AssetRegisterMaintenanceLogs> AssetRegisterMaintenanceLogsAllocatedTo { get; set; } = new List<AssetRegisterMaintenanceLogs>();

    public virtual ICollection<AssetRegisterMaintenanceLogs> AssetRegisterMaintenanceLogsCreatedBy { get; set; } = new List<AssetRegisterMaintenanceLogs>();

    public virtual ICollection<AssetRegister> AssetRegisterOwnedBy { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssetRegisterReservationComments> AssetRegisterReservationComments { get; set; } = new List<AssetRegisterReservationComments>();

    public virtual ICollection<AssetRegisterReservationReports> AssetRegisterReservationReports { get; set; } = new List<AssetRegisterReservationReports>();

    public virtual ICollection<AssetRegisterReservationTermsAndConditions> AssetRegisterReservationTermsAndConditions { get; set; } = new List<AssetRegisterReservationTermsAndConditions>();

    public virtual ICollection<AssetRegisterReservations> AssetRegisterReservationsCreatedBy { get; set; } = new List<AssetRegisterReservations>();

    public virtual ICollection<AssetRegisterReservations> AssetRegisterReservationsRequestedBy { get; set; } = new List<AssetRegisterReservations>();

    public virtual ICollection<AssetRegisterWarranties> AssetRegisterWarranties { get; set; } = new List<AssetRegisterWarranties>();

    public virtual ICollection<AssetSupplierComments> AssetSupplierComments { get; set; } = new List<AssetSupplierComments>();

    public virtual ICollection<AssetSupplierContacts> AssetSupplierContacts { get; set; } = new List<AssetSupplierContacts>();

    public virtual ICollection<AssetSuppliers> AssetSuppliers { get; set; } = new List<AssetSuppliers>();

    public virtual ICollection<AssuranceAutomatedControlTestDefinition> AssuranceAutomatedControlTestDefinition { get; set; } = new List<AssuranceAutomatedControlTestDefinition>();

    public virtual ICollection<AssuranceAutomatedControlTestExecutedOutcomes> AssuranceAutomatedControlTestExecutedOutcomes { get; set; } = new List<AssuranceAutomatedControlTestExecutedOutcomes>();

    public virtual ICollection<AssurancePrograms> AssuranceProgramsCreatedBy { get; set; } = new List<AssurancePrograms>();

    public virtual ICollection<AssurancePrograms> AssuranceProgramsOwner { get; set; } = new List<AssurancePrograms>();

    public virtual ICollection<AssuranceSchedule> AssuranceScheduleCreatedBy { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSchedule> AssuranceScheduleOwner { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceScheduleUsers> AssuranceScheduleUsersCreatedBy { get; set; } = new List<AssuranceScheduleUsers>();

    public virtual ICollection<AssuranceScheduleUsers> AssuranceScheduleUsersUser { get; set; } = new List<AssuranceScheduleUsers>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLog { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceSubmissionProcessed> AssuranceSubmissionProcessed { get; set; } = new List<AssuranceSubmissionProcessed>();

    public virtual ICollection<AssuranceSubmissionProcessedComments> AssuranceSubmissionProcessedComments { get; set; } = new List<AssuranceSubmissionProcessedComments>();

    public virtual ICollection<AssuranceTemplates> AssuranceTemplatesCreatedBy { get; set; } = new List<AssuranceTemplates>();

    public virtual ICollection<AssuranceTemplates> AssuranceTemplatesOwner { get; set; } = new List<AssuranceTemplates>();

    public virtual ICollection<AssuranceTemplatesScoringBands> AssuranceTemplatesScoringBands { get; set; } = new List<AssuranceTemplatesScoringBands>();

    public virtual ICollection<AssuranceVoiceTestTemplates> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplates>();

    public virtual ICollection<BCPLibrary> BCPLibraryCreatedBy { get; set; } = new List<BCPLibrary>();

    public virtual ICollection<BCPLibrary> BCPLibraryOwner { get; set; } = new List<BCPLibrary>();

    public virtual ICollection<BusinessContinuityPlansComments> BusinessContinuityPlansComments { get; set; } = new List<BusinessContinuityPlansComments>();

    public virtual ICollection<BusinessContinuityPlans> BusinessContinuityPlansCreatedBy { get; set; } = new List<BusinessContinuityPlans>();

    public virtual ICollection<BusinessContinuityPlans> BusinessContinuityPlansOwner { get; set; } = new List<BusinessContinuityPlans>();

    public virtual ICollection<ComplaintsOrComplimentsComments> ComplaintsOrComplimentsComments { get; set; } = new List<ComplaintsOrComplimentsComments>();

    public virtual ICollection<ComplaintsOrCompliments> ComplaintsOrComplimentsCreatedBy { get; set; } = new List<ComplaintsOrCompliments>();

    public virtual ICollection<ComplaintsOrCompliments> ComplaintsOrComplimentsOwner { get; set; } = new List<ComplaintsOrCompliments>();

    public virtual ICollection<CredScraperGoverningBodies> CredScraperGoverningBodies { get; set; } = new List<CredScraperGoverningBodies>();

    public virtual ICollection<CredScraperUserRecord> CredScraperUserRecordCreatedBy { get; set; } = new List<CredScraperUserRecord>();

    public virtual ICollection<CredScraperUserRecord> CredScraperUserRecordReportsToUser { get; set; } = new List<CredScraperUserRecord>();

    public virtual ICollection<CredentialsConditions> CredentialsConditions { get; set; } = new List<CredentialsConditions>();

    public virtual ICollection<CredentialsConditionsPeriodicAcknowledgement> CredentialsConditionsPeriodicAcknowledgementAcknowledgementBy { get; set; } = new List<CredentialsConditionsPeriodicAcknowledgement>();

    public virtual ICollection<CredentialsConditionsPeriodicAcknowledgement> CredentialsConditionsPeriodicAcknowledgementCreatedBy { get; set; } = new List<CredentialsConditionsPeriodicAcknowledgement>();

    public virtual ICollection<Credentials> CredentialsCreatdBy { get; set; } = new List<Credentials>();

    public virtual ICollection<Credentials> CredentialsGovernanceOwner { get; set; } = new List<Credentials>();

    public virtual ICollection<CredentialsNotations> CredentialsNotations { get; set; } = new List<CredentialsNotations>();

    public virtual ICollection<Credentials> CredentialsOwner { get; set; } = new List<Credentials>();

    public virtual ICollection<CredentialsRegulatoryBodies> CredentialsRegulatoryBodies { get; set; } = new List<CredentialsRegulatoryBodies>();

    public virtual ICollection<CredentialsReprimands> CredentialsReprimands { get; set; } = new List<CredentialsReprimands>();

    public virtual ICollection<CredentialsUndertakings> CredentialsUndertakings { get; set; } = new List<CredentialsUndertakings>();

    public virtual ICollection<CredentialsUserRegistrations> CredentialsUserRegistrationsCreatedBy { get; set; } = new List<CredentialsUserRegistrations>();

    public virtual ICollection<CredentialsUserRegistrations> CredentialsUserRegistrationsLineManagerUser { get; set; } = new List<CredentialsUserRegistrations>();

    public virtual ICollection<CredentialsUserRegistrations> CredentialsUserRegistrationsUser { get; set; } = new List<CredentialsUserRegistrations>();

    public virtual ICollection<Divisions> Divisions { get; set; } = new List<Divisions>();

    public virtual ICollection<DocsAccessLog> DocsAccessLog { get; set; } = new List<DocsAccessLog>();

    public virtual ICollection<Docs> DocsCreatedBy { get; set; } = new List<Docs>();

    public virtual ICollection<DocsDelegatedAuthorities> DocsDelegatedAuthoritiesCreatedBy { get; set; } = new List<DocsDelegatedAuthorities>();

    public virtual ICollection<DocsDelegatedAuthorities> DocsDelegatedAuthoritiesUser { get; set; } = new List<DocsDelegatedAuthorities>();

    public virtual ICollection<DocsItemComments> DocsItemComments { get; set; } = new List<DocsItemComments>();

    public virtual ICollection<DocsItems> DocsItemsCreatedBy { get; set; } = new List<DocsItems>();

    public virtual ICollection<DocsItemsExemptions> DocsItemsExemptionsCreatedBy { get; set; } = new List<DocsItemsExemptions>();

    public virtual ICollection<DocsItemsExemptions> DocsItemsExemptionsDecisionUser { get; set; } = new List<DocsItemsExemptions>();

    public virtual ICollection<DocsItemsExemptions> DocsItemsExemptionsRequestingUser { get; set; } = new List<DocsItemsExemptions>();

    public virtual ICollection<DocsItems> DocsItemsOwner { get; set; } = new List<DocsItems>();

    public virtual ICollection<DocsKnowledgeTransfer> DocsKnowledgeTransfer { get; set; } = new List<DocsKnowledgeTransfer>();

    public virtual ICollection<DocsKnowledgeTransferUsers> DocsKnowledgeTransferUsersCreatedBy { get; set; } = new List<DocsKnowledgeTransferUsers>();

    public virtual ICollection<DocsKnowledgeTransferUsers> DocsKnowledgeTransferUsersUser { get; set; } = new List<DocsKnowledgeTransferUsers>();

    public virtual ICollection<DocsLibraryItemsExemptionsConditions> DocsLibraryItemsExemptionsConditionsAcceptedByUser { get; set; } = new List<DocsLibraryItemsExemptionsConditions>();

    public virtual ICollection<DocsLibraryItemsExemptionsConditions> DocsLibraryItemsExemptionsConditionsCreatedBy { get; set; } = new List<DocsLibraryItemsExemptionsConditions>();

    public virtual ICollection<Docs> DocsOwner { get; set; } = new List<Docs>();

    public virtual ICollection<DocsRelatedChildArtifacts> DocsRelatedChildArtifacts { get; set; } = new List<DocsRelatedChildArtifacts>();

    public virtual ICollection<DocsReviews> DocsReviewsCreatedBy { get; set; } = new List<DocsReviews>();

    public virtual ICollection<DocsReviews> DocsReviewsOwner { get; set; } = new List<DocsReviews>();

    public virtual ICollection<DocsSubscriptionUsers> DocsSubscriptionUsersCreatedBy { get; set; } = new List<DocsSubscriptionUsers>();

    public virtual ICollection<DocsSubscriptionUsers> DocsSubscriptionUsersUser { get; set; } = new List<DocsSubscriptionUsers>();

    public virtual ICollection<DocstensExemptionsComments> DocstensExemptionsComments { get; set; } = new List<DocstensExemptionsComments>();

    public virtual ICollection<ImprovementTeamMembers> ImprovementTeamMembersCreatedBy { get; set; } = new List<ImprovementTeamMembers>();

    public virtual ICollection<ImprovementTeamMembers> ImprovementTeamMembersUser { get; set; } = new List<ImprovementTeamMembers>();

    public virtual ICollection<ImprovementTools> ImprovementTools { get; set; } = new List<ImprovementTools>();

    public virtual ICollection<ImprovementTypes> ImprovementTypes { get; set; } = new List<ImprovementTypes>();

    public virtual ICollection<Improvements> ImprovementsCreatedBy { get; set; } = new List<Improvements>();

    public virtual ICollection<ImprovementsDelivered> ImprovementsDelivered { get; set; } = new List<ImprovementsDelivered>();

    public virtual ICollection<ImprovementsObjectives> ImprovementsObjectivesCreatedBy { get; set; } = new List<ImprovementsObjectives>();

    public virtual ICollection<ImprovementsObjectives> ImprovementsObjectivesOwner { get; set; } = new List<ImprovementsObjectives>();

    public virtual ICollection<Improvements> ImprovementsOwner { get; set; } = new List<Improvements>();

    public virtual ICollection<IncidentsCannedBCPs> IncidentsCannedBCPs { get; set; } = new List<IncidentsCannedBCPs>();

    public virtual ICollection<IncidentsCannedReports> IncidentsCannedReports { get; set; } = new List<IncidentsCannedReports>();

    public virtual ICollection<IncidentsCategories> IncidentsCategories { get; set; } = new List<IncidentsCategories>();

    public virtual ICollection<Incidents> IncidentsCreatedBy { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsDivisionOwners> IncidentsDivisionOwnersCreatedBy { get; set; } = new List<IncidentsDivisionOwners>();

    public virtual ICollection<IncidentsDivisionOwners> IncidentsDivisionOwnersUser { get; set; } = new List<IncidentsDivisionOwners>();

    public virtual ICollection<IncidentsEmergencyResponseTypes> IncidentsEmergencyResponseTypes { get; set; } = new List<IncidentsEmergencyResponseTypes>();

    public virtual ICollection<IncidentsEmergencyResponses> IncidentsEmergencyResponses { get; set; } = new List<IncidentsEmergencyResponses>();

    public virtual ICollection<IncidentsExternalTeamMembers> IncidentsExternalTeamMembers { get; set; } = new List<IncidentsExternalTeamMembers>();

    public virtual ICollection<IncidentsFieldInvestigationCategoriesAndForms> IncidentsFieldInvestigationCategoriesAndForms { get; set; } = new List<IncidentsFieldInvestigationCategoriesAndForms>();

    public virtual ICollection<IncidentsFieldInvestigationSubmissionLog> IncidentsFieldInvestigationSubmissionLog { get; set; } = new List<IncidentsFieldInvestigationSubmissionLog>();

    public virtual ICollection<IncidentsFieldInvestigations> IncidentsFieldInvestigationsCreatedBy { get; set; } = new List<IncidentsFieldInvestigations>();

    public virtual ICollection<IncidentsFieldInvestigations> IncidentsFieldInvestigationsOwner { get; set; } = new List<IncidentsFieldInvestigations>();

    public virtual ICollection<IncidentsInternalTeamMembers> IncidentsInternalTeamMembersCreatedBy { get; set; } = new List<IncidentsInternalTeamMembers>();

    public virtual ICollection<IncidentsInternalTeamMembers> IncidentsInternalTeamMembersUser { get; set; } = new List<IncidentsInternalTeamMembers>();

    public virtual ICollection<IncidentsLessonsLearnt> IncidentsLessonsLearnt { get; set; } = new List<IncidentsLessonsLearnt>();

    public virtual ICollection<IncidentsLessonsLearntKeywords> IncidentsLessonsLearntKeywords { get; set; } = new List<IncidentsLessonsLearntKeywords>();

    public virtual ICollection<Incidents> IncidentsOwner { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsRPOLibrary> IncidentsRPOLibrary { get; set; } = new List<IncidentsRPOLibrary>();

    public virtual ICollection<IncidentsRTOLibrary> IncidentsRTOLibrary { get; set; } = new List<IncidentsRTOLibrary>();

    public virtual ICollection<IncidentsRTOLibraryLinkIncidents> IncidentsRTOLibraryLinkIncidentsCommentBy { get; set; } = new List<IncidentsRTOLibraryLinkIncidents>();

    public virtual ICollection<IncidentsRTOLibraryLinkIncidents> IncidentsRTOLibraryLinkIncidentsCreatedBy { get; set; } = new List<IncidentsRTOLibraryLinkIncidents>();

    public virtual ICollection<Incidents> IncidentsReportingUser { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsReports> IncidentsReports { get; set; } = new List<IncidentsReports>();

    public virtual ICollection<IncidentsReportsComments> IncidentsReportsComments { get; set; } = new List<IncidentsReportsComments>();

    public virtual ICollection<IncidentsSeverities> IncidentsSeverities { get; set; } = new List<IncidentsSeverities>();

    public virtual ICollection<IncidentsSnapChartCausalFactors> IncidentsSnapChartCausalFactors { get; set; } = new List<IncidentsSnapChartCausalFactors>();

    public virtual ICollection<IncidentsSnapChartLog> IncidentsSnapChartLog { get; set; } = new List<IncidentsSnapChartLog>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementsOfNeedCreatedBy { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementsOfNeedOwner { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual ICollection<InternalAuditPlan> InternalAuditPlanCreatedBy { get; set; } = new List<InternalAuditPlan>();

    public virtual ICollection<InternalAuditPlan> InternalAuditPlanOwner { get; set; } = new List<InternalAuditPlan>();

    public virtual ICollection<InternalAuditPlanResources> InternalAuditPlanResourcesCreatedBy { get; set; } = new List<InternalAuditPlanResources>();

    public virtual ICollection<InternalAuditPlanResources> InternalAuditPlanResourcesUser { get; set; } = new List<InternalAuditPlanResources>();

    public virtual ICollection<InternalAuditResources> InternalAuditResourcesCreatedBy { get; set; } = new List<InternalAuditResources>();

    public virtual ICollection<InternalAuditResources> InternalAuditResourcesUser { get; set; } = new List<InternalAuditResources>();

    public virtual ICollection<InternalAudits> InternalAuditsBusinessUnitCommentsBy { get; set; } = new List<InternalAudits>();

    public virtual ICollection<InternalAudits> InternalAuditsCreatedBy { get; set; } = new List<InternalAudits>();

    public virtual ICollection<InternalAudits> InternalAuditsOwner { get; set; } = new List<InternalAudits>();

    public virtual ICollection<IssuesActionTaskTypes> IssuesActionTaskTypesBaseOwner { get; set; } = new List<IssuesActionTaskTypes>();

    public virtual ICollection<IssuesActionTaskTypes> IssuesActionTaskTypesCreatedBy { get; set; } = new List<IssuesActionTaskTypes>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasksAllocatedTo { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<IssuesActionsTasksComments> IssuesActionsTasksComments { get; set; } = new List<IssuesActionsTasksComments>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasksCreatedBy { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverrideCreatedBy { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverrideOwner { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();

    public virtual ICollection<IssuesActionsTasksUrgencyAndOffset> IssuesActionsTasksUrgencyAndOffset { get; set; } = new List<IssuesActionsTasksUrgencyAndOffset>();

    public virtual ICollection<RegulatoryEngagementBody> RegulatoryEngagementBody { get; set; } = new List<RegulatoryEngagementBody>();

    public virtual ICollection<RegulatoryEngagementBodyContacts> RegulatoryEngagementBodyContacts { get; set; } = new List<RegulatoryEngagementBodyContacts>();

    public virtual ICollection<RegulatoryEngagementEventLog> RegulatoryEngagementEventLog { get; set; } = new List<RegulatoryEngagementEventLog>();

    public virtual ICollection<RegulatoryEngagementResources> RegulatoryEngagementResourcesCreatedBy { get; set; } = new List<RegulatoryEngagementResources>();

    public virtual ICollection<RegulatoryEngagementResources> RegulatoryEngagementResourcesUser { get; set; } = new List<RegulatoryEngagementResources>();

    public virtual ICollection<RegulatoryEngagements> RegulatoryEngagementsCreatedBy { get; set; } = new List<RegulatoryEngagements>();

    public virtual ICollection<RegulatoryEngagementsOutcomes> RegulatoryEngagementsOutcomes { get; set; } = new List<RegulatoryEngagementsOutcomes>();

    public virtual ICollection<RegulatoryEngagements> RegulatoryEngagementsOwner { get; set; } = new List<RegulatoryEngagements>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveryAccountableOwner { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScope { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RiskDiscoveryControlScopeDesignEffectiveness> RiskDiscoveryControlScopeDesignEffectiveness { get; set; } = new List<RiskDiscoveryControlScopeDesignEffectiveness>();

    public virtual ICollection<RiskDiscoveryControlScopeOperatingEffectiveness> RiskDiscoveryControlScopeOperatingEffectiveness { get; set; } = new List<RiskDiscoveryControlScopeOperatingEffectiveness>();

    public virtual ICollection<RiskDiscovery> RiskDiscoveryCretedBy { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryResources> RiskDiscoveryResourcesCreatedBy { get; set; } = new List<RiskDiscoveryResources>();

    public virtual ICollection<RiskDiscoveryResources> RiskDiscoveryResourcesUser { get; set; } = new List<RiskDiscoveryResources>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopeCreatedBy { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RiskDiscoveryScopeInherentAndResidualAssessments> RiskDiscoveryScopeInherentAndResidualAssessments { get; set; } = new List<RiskDiscoveryScopeInherentAndResidualAssessments>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScopeRiskOwner { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RisksControlSuggestionComments> RisksControlSuggestionComments { get; set; } = new List<RisksControlSuggestionComments>();

    public virtual ICollection<RisksControlSuggestions> RisksControlSuggestions { get; set; } = new List<RisksControlSuggestions>();

    public virtual ICollection<RisksControls> RisksControlsCreatedBy { get; set; } = new List<RisksControls>();

    public virtual ICollection<RisksControls> RisksControlsOwner { get; set; } = new List<RisksControls>();

    public virtual ICollection<Risks> RisksCreatedBy { get; set; } = new List<Risks>();

    public virtual ICollection<RisksMatirxsConcequenceLabels> RisksMatirxsConcequenceLabels { get; set; } = new List<RisksMatirxsConcequenceLabels>();

    public virtual ICollection<RisksMatirxsLikelihoodLabels> RisksMatirxsLikelihoodLabels { get; set; } = new List<RisksMatirxsLikelihoodLabels>();

    public virtual ICollection<RisksMatrixLikelihoodConsequenceFields> RisksMatrixLikelihoodConsequenceFields { get; set; } = new List<RisksMatrixLikelihoodConsequenceFields>();

    public virtual ICollection<RisksMatrixs> RisksMatrixs { get; set; } = new List<RisksMatrixs>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RisksOwnedRiskAutomatedControlTestBatch { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes> RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestDefinition> RisksOwnedRiskAutomatedControlTestDefinition { get; set; } = new List<RisksOwnedRiskAutomatedControlTestDefinition>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRiskCreatedBy { get; set; } = new List<RisksOwnedRisk>();

    public virtual ICollection<RisksOwnedRiskInherentAndRedisualAssessment> RisksOwnedRiskInherentAndRedisualAssessment { get; set; } = new List<RisksOwnedRiskInherentAndRedisualAssessment>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness> RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentUsers> RisksOwnedRiskInherentAndResidualAssessmentUsersCreatedBy { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentUsers>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentUsers> RisksOwnedRiskInherentAndResidualAssessmentUsersUser { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentUsers>();

    public virtual ICollection<RisksOwnedRiskInherentResidualRiskAnalysis> RisksOwnedRiskInherentResidualRiskAnalysis { get; set; } = new List<RisksOwnedRiskInherentResidualRiskAnalysis>();

    public virtual ICollection<RisksOwnedRiskInherentRiskAnalysis> RisksOwnedRiskInherentRiskAnalysis { get; set; } = new List<RisksOwnedRiskInherentRiskAnalysis>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRiskOwner { get; set; } = new List<RisksOwnedRisk>();

    public virtual ICollection<RisksOwnedRiskResidualRiskAnalysis> RisksOwnedRiskResidualRiskAnalysis { get; set; } = new List<RisksOwnedRiskResidualRiskAnalysis>();

    public virtual ICollection<Risks> RisksOwner { get; set; } = new List<Risks>();

    public virtual ICollection<RisksStandardsActs> RisksStandardsActs { get; set; } = new List<RisksStandardsActs>();

    public virtual ICollection<RisksSuggestionComments> RisksSuggestionComments { get; set; } = new List<RisksSuggestionComments>();

    public virtual ICollection<RisksSuggestions> RisksSuggestionsCreatedBy { get; set; } = new List<RisksSuggestions>();

    public virtual ICollection<RisksSuggestions> RisksSuggestionsOwner { get; set; } = new List<RisksSuggestions>();

    public virtual ICollection<AspNetRoles> Role { get; set; } = new List<AspNetRoles>();
}