// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterReservations
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public Guid AssetRegisterReservationTermsAndConditionsId { get; set; }

    public string DisplayId { get; set; }

    public DateTime RequestedDt { get; set; }

    public string RequestedById { get; set; }

    public DateTime PlannedReturnDt { get; set; }

    public string IntendedUseDescription { get; set; }

    public DateTime? ReturnedDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual ICollection<AssetRegisterIssuesLogs> AssetRegisterIssuesLogs { get; set; } = new List<AssetRegisterIssuesLogs>();

    public virtual ICollection<AssetRegisterReservationComments> AssetRegisterReservationComments { get; set; } = new List<AssetRegisterReservationComments>();

    public virtual ICollection<AssetRegisterReservationReports> AssetRegisterReservationReports { get; set; } = new List<AssetRegisterReservationReports>();

    public virtual AssetRegisterReservationTermsAndConditions AssetRegisterReservationTermsAndConditions { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers RequestedBy { get; set; }
}