// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterInspectionSchedules
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public string DisplayId { get; set; }

    public DateTime RequiredInspectionDt { get; set; }

    public DateTime? NextInspectionDt { get; set; }

    public string InspectionDescription { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual ICollection<AssetRegisterInspectionScheduleComments> AssetRegisterInspectionScheduleComments { get; set; } = new List<AssetRegisterInspectionScheduleComments>();

    public virtual AspNetUsers CreatedBy { get; set; }
}