// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetSuppliers
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Web { get; set; }

    public string KeyWords { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public Guid AssetSupplierTypeId { get; set; }

    public virtual ICollection<AssetPurchaseOrders> AssetPurchaseOrders { get; set; } = new List<AssetPurchaseOrders>();

    public virtual ICollection<AssetRegister> AssetRegister { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssetSupplierComments> AssetSupplierComments { get; set; } = new List<AssetSupplierComments>();

    public virtual ICollection<AssetSupplierContacts> AssetSupplierContacts { get; set; } = new List<AssetSupplierContacts>();

    public virtual AssetSupplierTypes AssetSupplierType { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }
}