// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterDepreciationSceduleItems
{
    public Guid Id { get; set; }

    public Guid AssetRegisterDepreciationScheduleId { get; set; }

    public string DisplayId { get; set; }

    public string FinancialYear { get; set; }

    public double WrittenDownValue { get; set; }

    public double DepreciationClaimValue { get; set; }

    public double CarriedValue { get; set; }

    public string Currency { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegisterDepreciationSchedule AssetRegisterDepreciationSchedule { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }
}