// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterReservationComments
{
    public Guid Id { get; set; }

    public Guid AssetRegisterReservationId { get; set; }

    public string DisplayId { get; set; }

    public string Comment { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegisterReservations AssetRegisterReservation { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }
}