// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegister
{
    public Guid Id { get; set; }

    public Guid AssetSupplierId { get; set; }

    public Guid? AssetPurchaseOrderId { get; set; }

    public Guid AssetCategoryId { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid PrimaryLocationId { get; set; }

    public string LocationDetails { get; set; }

    public string OwnedById { get; set; }

    public DateTime RegistrationDate { get; set; }

    public DateTime DepreciationDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegisterCategories AssetCategory { get; set; }

    public virtual AssetPurchaseOrders AssetPurchaseOrder { get; set; }

    public virtual ICollection<AssetRegisterComments> AssetRegisterComments { get; set; } = new List<AssetRegisterComments>();

    public virtual ICollection<AssetRegisterDepreciationSchedule> AssetRegisterDepreciationSchedule { get; set; } = new List<AssetRegisterDepreciationSchedule>();

    public virtual ICollection<AssetRegisterInspectionSchedules> AssetRegisterInspectionSchedules { get; set; } = new List<AssetRegisterInspectionSchedules>();

    public virtual ICollection<AssetRegisterIssuesLogs> AssetRegisterIssuesLogs { get; set; } = new List<AssetRegisterIssuesLogs>();

    public virtual ICollection<AssetRegisterMaintenanceLogs> AssetRegisterMaintenanceLogs { get; set; } = new List<AssetRegisterMaintenanceLogs>();

    public virtual ICollection<AssetRegisterReservationTermsAndConditions> AssetRegisterReservationTermsAndConditions { get; set; } = new List<AssetRegisterReservationTermsAndConditions>();

    public virtual ICollection<AssetRegisterReservations> AssetRegisterReservations { get; set; } = new List<AssetRegisterReservations>();

    public virtual ICollection<AssetRegisterWarranties> AssetRegisterWarranties { get; set; } = new List<AssetRegisterWarranties>();

    public virtual AssetSuppliers AssetSupplier { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers OwnedBy { get; set; }

    public virtual Divisions PrimaryLocation { get; set; }
}