// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterDepreciationSchedule
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public Guid AssetDepreciationScheduleDisposalCodeId { get; set; }

    public string DisplayId { get; set; }

    public string EffectiveLife { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public double InitialValue { get; set; }

    public double ResidualValue { get; set; }

    public string Country { get; set; }

    public string Currency { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegisterDepreciationScheduleDisposalCodes AssetDepreciationScheduleDisposalCode { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual ICollection<AssetRegisterDepreciationSceduleItems> AssetRegisterDepreciationSceduleItems { get; set; } = new List<AssetRegisterDepreciationSceduleItems>();

    public virtual AspNetUsers CreatedBy { get; set; }
}