// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetPurchaseOrders
{
    public Guid Id { get; set; }

    public Guid AssetSupplierId { get; set; }

    public string DisplayId { get; set; }

    public string SupplierOrderReference { get; set; }

    public DateTime PurchaseDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double Amount { get; set; }

    public string Currency { get; set; }

    public string TaxCode { get; set; }

    public double TaxAmount { get; set; }

    public string PurchaseOrderApprovedById { get; set; }

    public DateTime? PurchaseOrderApprovalDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssetPurchaseOrderItems> AssetPurchaseOrderItems { get; set; } = new List<AssetPurchaseOrderItems>();

    public virtual ICollection<AssetPurchaseOrderTransactions> AssetPurchaseOrderTransactions { get; set; } = new List<AssetPurchaseOrderTransactions>();

    public virtual ICollection<AssetRegister> AssetRegister { get; set; } = new List<AssetRegister>();

    public virtual AssetSuppliers AssetSupplier { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers PurchaseOrderApprovedBy { get; set; }
}