// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetSupplierTypes
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string BusinessTypeCode { get; set; }

    public string Country { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssetSuppliers> AssetSuppliers { get; set; } = new List<AssetSuppliers>();
}