// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterMaintenanceLogs
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public Guid? AssetRegisterIssuesLogId { get; set; }

    public Guid AssetRegisterMaintenanceLogTypeId { get; set; }

    public string AllocatedToId { get; set; }

    public DateTime RequestedDt { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? CompletedDt { get; set; }

    public string Description { get; set; }

    public double? ComponentCosts { get; set; }

    public double? LaborCosts { get; set; }

    public double? TotalCosts { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public virtual AspNetUsers AllocatedTo { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual AssetRegisterIssuesLogs AssetRegisterIssuesLog { get; set; }

    public virtual ICollection<AssetRegisterMaintenanceLogComments> AssetRegisterMaintenanceLogComments { get; set; } = new List<AssetRegisterMaintenanceLogComments>();

    public virtual AssetRegisterMaintenanceLogTypes AssetRegisterMaintenanceLogType { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssueActionTask { get; set; } = new List<IssuesActionsTasks>();
}