// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssetRegisterReservationTermsAndConditions
{
    public Guid Id { get; set; }

    public Guid AssetRegisterId { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssetRegister AssetRegister { get; set; }

    public virtual ICollection<AssetRegisterReservations> AssetRegisterReservations { get; set; } = new List<AssetRegisterReservations>();

    public virtual AspNetUsers CreatedBy { get; set; }
}