// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceSubmissionProcessedResponsesDocsWeightings
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceSubmissionProcessedId { get; set; }

    public int QuestionOrderId { get; set; }

    public string QuestionIdentifier { get; set; }

    public string QuestionText { get; set; }

    public string Answer { get; set; }

    public string indicator { get; set; }

    public Guid DocsId { get; set; }

    public double Weighting { get; set; }
}