// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssurancePrograms
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreateedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssuranceSchedule> AssuranceSchedule { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLog { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceTemplates> AssuranceTemplates { get; set; } = new List<AssuranceTemplates>();

    public virtual ICollection<AssuranceVoiceTestTemplates> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplates>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }
}