// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceAutomatedControlTestExecutedOutcomes
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceAutomatedControlTestBatchRunId { get; set; }

    public int RunNumber { get; set; }

    public int QuestionOrderId { get; set; }

    public string QuestionIdentifier { get; set; }

    public string QuestionText { get; set; }

    public string AssuranceAnswer { get; set; }

    public string TestType { get; set; }

    public string TextValues { get; set; }

    public int TestOutcome { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssuranceAutomatedControlTestBatchRun AssuranceAutomatedControlTestBatchRun { get; set; }

    public virtual AspNetUsers CreatedByNavigation { get; set; }
}