// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceTemplates
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceProgramId { get; set; }

    public string Name { get; set; }

    public string TemplateJSON { get; set; }

    public string OwnerId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreaetdDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfig { get; set; } = new List<APISECollectionTestConfig>();

    public virtual AssurancePrograms AssuranceProgram { get; set; }

    public virtual ICollection<AssuranceSchedule> AssuranceSchedule { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLog { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceSubmissionProcessed> AssuranceSubmissionProcessed { get; set; } = new List<AssuranceSubmissionProcessed>();

    public virtual ICollection<AssuranceTemplatesScoringBands> AssuranceTemplatesScoringBands { get; set; } = new List<AssuranceTemplatesScoringBands>();

    public virtual ICollection<AssuranceVoiceTestTemplates> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplates>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }
}