// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceScheduleUsers
{
    public Guid Id { get; set; }

    public Guid AssuranceScheduleId { get; set; }

    public string UserId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AssuranceSchedule AssuranceSchedule { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers User { get; set; }
}