// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceSubmissionprocessedResponsesStructuredAnswers
{
    public Guid Id { get; set; }

    public Guid AssuranceSubmissionProcessedResponsesStructuredId { get; set; }

    public string Answer { get; set; }

    public double ContributionScore { get; set; }

    public string AnswerFGColor { get; set; }

    public string AnswerBGColor { get; set; }

    public virtual AssuranceSubmissionProcessedResponsesStructured AssuranceSubmissionProcessedResponsesStructured { get; set; }
}