// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceSubmissionProcessedVoiceTranscriptionAndSentiment
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceSubmissionProcessedId { get; set; }

    public string TranscribedText { get; set; }

    public string Timestamp { get; set; }

    public double? Sentiment { get; set; }

    public virtual AssuranceSubmissionProcessed AssuranceSubmissionProcessed { get; set; }
}