// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceSchedule
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceProgramId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public string OwnerId { get; set; }

    public Guid DivisionId { get; set; }

    public DateTime StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public int Frequency { get; set; }

    public string FrequencySettings { get; set; }

    public int AutoCleanup { get; set; }

    public int? IncompleteAuditExpiry { get; set; }

    public int IncludeQuotas { get; set; }

    public int? QuotaQuantity { get; set; }

    public int? QuotaTotal { get; set; }

    public int SetReminders { get; set; }

    public int? OwnerCommencementReminder { get; set; }

    public int? OwnerCompletionReminder { get; set; }

    public int? CollectorCommencementReminder { get; set; }

    public int? CollectorCompletionReminder { get; set; }

    public int EnableSelfSubscribe { get; set; }

    public int EnableExternalAccess { get; set; }

    public int ScheduleEnabled { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public int ExternalAccessReload { get; set; }

    public int? FilteredDivisions { get; set; }

    public string DivisionsFilter { get; set; }

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfig { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<AssuranceAutomatedControlTestDefinition> AssuranceAutomatedControlTestDefinition { get; set; } = new List<AssuranceAutomatedControlTestDefinition>();

    public virtual AssurancePrograms AssuranceProgram { get; set; }

    public virtual ICollection<AssuranceScheduleUsers> AssuranceScheduleUsers { get; set; } = new List<AssuranceScheduleUsers>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLog { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual AssuranceTemplates AssuranceTemplate { get; set; }

    public virtual ICollection<AssuranceVoiceTestTemplates> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplates>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();
}