// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceSubmissionProcessedResponsesUnStructuredAnswers
{
    public Guid Id { get; set; }

    public Guid AssuranceSubmissionProcessedResponsesUnStructuredId { get; set; }

    public string Answer { get; set; }

    public double ContributionScore { get; set; }

    public string AnswerFGColor { get; set; }

    public string AnswerBGColor { get; set; }

    public bool? SentimentIsPositive { get; set; }

    public double? SentimentConfidence { get; set; }

    public virtual AssuranceSubmissionProcessedResponsesUnStructured AssuranceSubmissionProcessedResponsesUnStructured { get; set; }
}