// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceSubmissionProcessed
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public Guid AssuranceSubmissionLogId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public double ContributionScore { get; set; }

    public double ContributionMaxScore { get; set; }

    public double ContributionPercentage { get; set; }

    public string ScoringBandName { get; set; }

    public string ScoringBandBGColor { get; set; }

    public string ScoringBandFGColor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssuranceSubmissionProcessedComments> AssuranceSubmissionProcessedComments { get; set; } = new List<AssuranceSubmissionProcessedComments>();

    public virtual ICollection<AssuranceSubmissionProcessedGroupings> AssuranceSubmissionProcessedGroupings { get; set; } = new List<AssuranceSubmissionProcessedGroupings>();

    public virtual ICollection<AssuranceSubmissionProcessedResponsesStructured> AssuranceSubmissionProcessedResponsesStructured { get; set; } = new List<AssuranceSubmissionProcessedResponsesStructured>();

    public virtual ICollection<AssuranceSubmissionProcessedResponsesUnStructured> AssuranceSubmissionProcessedResponsesUnStructured { get; set; } = new List<AssuranceSubmissionProcessedResponsesUnStructured>();

    public virtual ICollection<AssuranceSubmissionProcessedRisksStandardsActsWeightings> AssuranceSubmissionProcessedRisksStandardsActsWeightings { get; set; } = new List<AssuranceSubmissionProcessedRisksStandardsActsWeightings>();

    public virtual ICollection<AssuranceSubmissionProcessedVoiceTranscriptionAndSentiment> AssuranceSubmissionProcessedVoiceTranscriptionAndSentiment { get; set; } = new List<AssuranceSubmissionProcessedVoiceTranscriptionAndSentiment>();

    public virtual AssuranceTemplates AssuranceTemplate { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }
}