// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class AssuranceAutomatedControlTestBatchRun
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceAutomatedControlTestDefinitionId { get; set; }

    public int RunNumber { get; set; }

    public DateTime RunStartDT { get; set; }

    public DateTime? RunEndDT { get; set; }

    public int TestsPassed { get; set; }

    public int TestsFailed { get; set; }

    public int IssuesRaised { get; set; }

    public virtual AssuranceAutomatedControlTestDefinition AssuranceAutomatedControlTestDefinition { get; set; }

    public virtual ICollection<AssuranceAutomatedControlTestExecutedOutcomes> AssuranceAutomatedControlTestExecutedOutcomes { get; set; } = new List<AssuranceAutomatedControlTestExecutedOutcomes>();

    public virtual ICollection<IssuesActionsTasks> IssueActionTask { get; set; } = new List<IssuesActionsTasks>();
}