// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class BCPLibrary
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string BCPJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<BusinessContinuityPlans> BusinessContinuityPlans { get; set; } = new List<BusinessContinuityPlans>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<IncidentsCannedBCPs> IncidentsCannedBCPs { get; set; } = new List<IncidentsCannedBCPs>();

    public virtual AspNetUsers Owner { get; set; }
}