// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class BusinessContinuityPlansLinkActionTasks
{
    public Guid BusinessContinuityPlanId { get; set; }

    public Guid IssuesActionsTasksActionId { get; set; }

    public Guid IssuesActionsTasksTaskId { get; set; }

    public virtual BusinessContinuityPlans BusinessContinuityPlan { get; set; }

    public virtual IssuesActionsTasks IssuesActionsTasksAction { get; set; }

    public virtual IssuesActionsTasks IssuesActionsTasksTask { get; set; }
}