// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class BusinessContinuityPlans
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid? IncidentId { get; set; }

    public Guid BCPLibraryId { get; set; }

    public DateTime StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string BCPJSON { get; set; }

    public double CompletionPercentage { get; set; }

    public string OwnerId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual BCPLibrary BCPLibrary { get; set; }

    public virtual ICollection<BusinessContinuityPlansComments> BusinessContinuityPlansComments { get; set; } = new List<BusinessContinuityPlansComments>();

    public virtual ICollection<BusinessContinuityPlansLinkActionTasks> BusinessContinuityPlansLinkActionTasks { get; set; } = new List<BusinessContinuityPlansLinkActionTasks>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssueActionTask { get; set; } = new List<IssuesActionsTasks>();
}