// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class ComplaintsOrCompliments
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public int Type { get; set; }

    public string Contact { get; set; }

    public string ContactAddress { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string Commentary { get; set; }

    public string OwnerId { get; set; }

    public string InitialResponse { get; set; }

    public int? Priority { get; set; }

    public DateTime? ResolutionRequiredDt { get; set; }

    public DateTime? ResolutionDt { get; set; }

    public string Outcome { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<ComplaintsOrComplimentsComments> ComplaintsOrComplimentsComments { get; set; } = new List<ComplaintsOrComplimentsComments>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}