// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class ComplaintsOrComplimentsComments
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid ComplaintsOrComplimentsId { get; set; }

    public string Comment { get; set; }

    public string CratedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ComplaintsOrCompliments ComplaintsOrCompliments { get; set; }

    public virtual AspNetUsers CratedBy { get; set; }
}