// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class Credentials
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string GovernanceOwnerId { get; set; }

    public Guid? ParentId { get; set; }

    public string Name { get; set; }

    public string RegistrationNumber { get; set; }

    public string GrantingBody { get; set; }

    public string CredentialStatus { get; set; }

    public DateTime DateOfObtainment { get; set; }

    public DateTime? DateOfExpiry { get; set; }

    public string PrinciplePlaceOfProfession { get; set; }

    public string PrincilePlaceOfProfessionAddress { get; set; }

    public string CreatdById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatdBy { get; set; }

    public virtual ICollection<CredentialsConditions> CredentialsConditions { get; set; } = new List<CredentialsConditions>();

    public virtual ICollection<CredentialsNotations> CredentialsNotations { get; set; } = new List<CredentialsNotations>();

    public virtual ICollection<CredentialsReprimands> CredentialsReprimands { get; set; } = new List<CredentialsReprimands>();

    public virtual ICollection<CredentialsUndertakings> CredentialsUndertakings { get; set; } = new List<CredentialsUndertakings>();

    public virtual AspNetUsers GovernanceOwner { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}