// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class CredentialsReprimands
{
    public Guid Id { get; set; }

    public Guid CredentialsId { get; set; }

    public string DisplayId { get; set; }

    public string Description { get; set; }

    public DateTime ReprimandEffectiveDate { get; set; }

    public DateTime? RepremandCompletionDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Credentials Credentials { get; set; }
}