// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class CredScraperFiles
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string FileName { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Records { get; set; }

    public int Status { get; set; }
}