// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class CredentialsUserRegistrations
{
    public Guid Id { get; set; }

    public Guid CredentialsId { get; set; }

    public Guid CredentialsRegulatoryBodyId { get; set; }

    public string DisplayId { get; set; }

    public string LineManagerUserId { get; set; }

    public string UserId { get; set; }

    public string RegistrationRef { get; set; }

    public string ScrapedInFile { get; set; }

    public DateTime? LastScrapedDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual CredentialsRegulatoryBodies CredentialsRegulatoryBody { get; set; }

    public virtual AspNetUsers LineManagerUser { get; set; }

    public virtual AspNetUsers User { get; set; }
}