// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class CredentialsConditionsPeriodicAcknowledgement
{
    public Guid Id { get; set; }

    public Guid CredentialsConditionId { get; set; }

    public string DisplayId { get; set; }

    public DateTime SentDate { get; set; }

    public DateTime DueDate { get; set; }

    public string SentTo { get; set; }

    public string SentSubject { get; set; }

    public string SentBody { get; set; }

    public string AcknowledgementById { get; set; }

    public DateTime? AcknoweledgementDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers AcknowledgementBy { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual CredentialsConditions CredentialsCondition { get; set; }
}