// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class Divisions
{
    public Guid Id { get; set; }

    public Guid? ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string DisplayId { get; set; }

    public virtual ICollection<APISECollectionTestConfig> APISECollectionTestConfig { get; set; } = new List<APISECollectionTestConfig>();

    public virtual ICollection<AssetRegister> AssetRegister { get; set; } = new List<AssetRegister>();

    public virtual ICollection<AssuranceSchedule> AssuranceSchedule { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<AssuranceSubmissionLog> AssuranceSubmissionLog { get; set; } = new List<AssuranceSubmissionLog>();

    public virtual ICollection<AssuranceSubmissionProcessed> AssuranceSubmissionProcessed { get; set; } = new List<AssuranceSubmissionProcessed>();

    public virtual ICollection<AssuranceVoiceTestTemplates> AssuranceVoiceTestTemplates { get; set; } = new List<AssuranceVoiceTestTemplates>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<Improvements> Improvements { get; set; } = new List<Improvements>();

    public virtual ICollection<Incidents> Incidents { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsDivisionOwners> IncidentsDivisionOwners { get; set; } = new List<IncidentsDivisionOwners>();

    public virtual ICollection<InternalAuditPlan> InternalAuditPlan { get; set; } = new List<InternalAuditPlan>();

    public virtual ICollection<InternalAudits> InternalAudits { get; set; } = new List<InternalAudits>();

    public virtual ICollection<Divisions> InverseParent { get; set; } = new List<Divisions>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverride { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();

    public virtual Divisions Parent { get; set; }

    public virtual ICollection<RegulatoryEngagements> RegulatoryEngagements { get; set; } = new List<RegulatoryEngagements>();

    public virtual ICollection<RiskDiscovery> RiskDiscovery { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScope { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRisk { get; set; } = new List<RisksOwnedRisk>();
}