// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class DocsLibraryItemsExemptionsConditions
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsItemsExemptionId { get; set; }

    public string Condution { get; set; }

    public int? AcceptanceStatus { get; set; }

    public string AcceptedByUserId { get; set; }

    public DateTime? AcceptedDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers AcceptedByUser { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual DocsItemsExemptions DocsItemsExemption { get; set; }
}