// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class DocsReviews
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public Guid DocsItemId { get; set; }

    public string OwnerId { get; set; }

    public DateTime ReviewDt { get; set; }

    public DateTime? ReviewCompletedDt { get; set; }

    public DateTime? NextRevewDt { get; set; }

    public string ReviewCommentary { get; set; }

    public string ReviewOutcome { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Docs Docs { get; set; }

    public virtual DocsItems DocsItem { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}