// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class DocsKnowledgeTransfer
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public Guid DocsItemId { get; set; }

    public bool IncludeDelegates { get; set; }

    public bool IncludeSubscribers { get; set; }

    public string ReadReceiptStatement { get; set; }

    public DateTime RequestDt { get; set; }

    public DateTime RequiredDt { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Docs Docs { get; set; }

    public virtual DocsItems DocsItem { get; set; }

    public virtual ICollection<DocsKnowledgeTransferUsers> DocsKnowledgeTransferUsers { get; set; } = new List<DocsKnowledgeTransferUsers>();
}