// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class Docs
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string DisplayPath { get; set; }

    public int ItemType { get; set; }

    public string Name { get; set; }

    public Guid? ParentId { get; set; }

    public int AccessLevel { get; set; }

    public string OwnerId { get; set; }

    public string Description { get; set; }

    public string KeyWords { get; set; }

    public string RecommendedFor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<DocsAccessLog> DocsAccessLog { get; set; } = new List<DocsAccessLog>();

    public virtual ICollection<DocsDelegatedAuthorities> DocsDelegatedAuthorities { get; set; } = new List<DocsDelegatedAuthorities>();

    public virtual ICollection<DocsItems> DocsItems { get; set; } = new List<DocsItems>();

    public virtual ICollection<DocsKnowledgeTransfer> DocsKnowledgeTransfer { get; set; } = new List<DocsKnowledgeTransfer>();

    public virtual ICollection<DocsRelatedChildArtifacts> DocsRelatedChildArtifacts { get; set; } = new List<DocsRelatedChildArtifacts>();

    public virtual ICollection<DocsReviews> DocsReviews { get; set; } = new List<DocsReviews>();

    public virtual ICollection<DocsSubscriptionUsers> DocsSubscriptionUsers { get; set; } = new List<DocsSubscriptionUsers>();

    public virtual ICollection<Docs> InverseParent { get; set; } = new List<Docs>();

    public virtual AspNetUsers Owner { get; set; }

    public virtual Docs Parent { get; set; }

    public virtual ICollection<Risks> Risk { get; set; } = new List<Risks>();
}