// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class DocsItems
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public string OwnerId { get; set; }

    public string Version { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ReleaseNotes { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreaedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Docs Docs { get; set; }

    public virtual ICollection<DocsItemComments> DocsItemComments { get; set; } = new List<DocsItemComments>();

    public virtual ICollection<DocsItemsExemptions> DocsItemsExemptions { get; set; } = new List<DocsItemsExemptions>();

    public virtual ICollection<DocsKnowledgeTransfer> DocsKnowledgeTransfer { get; set; } = new List<DocsKnowledgeTransfer>();

    public virtual ICollection<DocsRelatedChildArtifacts> DocsRelatedChildArtifacts { get; set; } = new List<DocsRelatedChildArtifacts>();

    public virtual ICollection<DocsReviews> DocsReviews { get; set; } = new List<DocsReviews>();

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}