// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class DocsSubscriptionUsers
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DocsId { get; set; }

    public string UserId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreaetdDt { get; set; }

    public DateTime? ExpiresDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Docs Docs { get; set; }

    public virtual AspNetUsers User { get; set; }
}