// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class ImprovementsObjectives
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid ImprovementId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Measurement { get; set; }

    public string Baseline { get; set; }

    public string Target { get; set; }

    public string OutcomeAssessment { get; set; }

    public string QualitativeAssessment { get; set; }

    public string QuantitativeAssessment { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Improvements Improvement { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}