// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class Improvements
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public Guid DivisionId { get; set; }

    public int Priority { get; set; }

    public DateTime RequiredCompletionDate { get; set; }

    public int PDSAPhaseStatus { get; set; }

    public int ImprovementStatus { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid ImprovementTypeId { get; set; }

    public string StrategyDescription { get; set; }

    public string CalculatedQualitative { get; set; }

    public string CalulatedQuantitative { get; set; }

    public string SubmittedQualitative { get; set; }

    public string SubmittedQuantitative { get; set; }

    public string DeliveredImprovementDescription { get; set; }

    public string FollowUpActionsRequried { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string KeyWords { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual ICollection<ImprovementTeamMembers> ImprovementTeamMembers { get; set; } = new List<ImprovementTeamMembers>();

    public virtual ImprovementTypes ImprovementType { get; set; }

    public virtual ICollection<ImprovementsDelivered> ImprovementsDelivered { get; set; } = new List<ImprovementsDelivered>();

    public virtual ICollection<ImprovementsObjectives> ImprovementsObjectives { get; set; } = new List<ImprovementsObjectives>();

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<AssuranceSchedule> AssuranceSchedule { get; set; } = new List<AssuranceSchedule>();

    public virtual ICollection<ComplaintsOrCompliments> ComplaintOrCompliment { get; set; } = new List<ComplaintsOrCompliments>();

    public virtual ICollection<Improvements> ImprovementChild { get; set; } = new List<Improvements>();

    public virtual ICollection<Improvements> ImprovementParent { get; set; } = new List<Improvements>();

    public virtual ICollection<Incidents> Incident { get; set; } = new List<Incidents>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<RiskDiscovery> RiskDiscovery { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RisksOwnedRiskInherentAndRedisualAssessment> RiskOwnedRiskInherentAndResidualRiskAssessment { get; set; } = new List<RisksOwnedRiskInherentAndRedisualAssessment>();

    public virtual ICollection<RisksStandardsActs> RisksStandardsActs { get; set; } = new List<RisksStandardsActs>();
}