// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class Incidents
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public string ReportingUserId { get; set; }

    public int IncidentTypeId { get; set; }

    public Guid? IncidentCategoryId { get; set; }

    public Guid? IncidentSeverityId { get; set; }

    public string ContactPerson { get; set; }

    public string ContactDetails { get; set; }

    public DateTime ReportedDt { get; set; }

    public string Description { get; set; }

    public string MaximumReasonableOutcome { get; set; }

    public int? MROAssessment { get; set; }

    public string MROOverride { get; set; }

    public int EmergencyResponseCalled { get; set; }

    public string OwnerId { get; set; }

    public string ImmediateActionsTaken { get; set; }

    public string SummaryInvolved { get; set; }

    public string SummaryResultedIn { get; set; }

    public string SummaryMayHaveResultedIn { get; set; }

    public string SummaryResponseSummary { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public DateTime? CompletedDt { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual IncidentsCategories IncidentCategory { get; set; }

    public virtual IncidentsSeverities IncidentSeverity { get; set; }

    public virtual ICollection<IncidentsEmergencyResponses> IncidentsEmergencyResponses { get; set; } = new List<IncidentsEmergencyResponses>();

    public virtual ICollection<IncidentsExternalTeamMembers> IncidentsExternalTeamMembers { get; set; } = new List<IncidentsExternalTeamMembers>();

    public virtual ICollection<IncidentsFieldInvestigations> IncidentsFieldInvestigations { get; set; } = new List<IncidentsFieldInvestigations>();

    public virtual ICollection<IncidentsInternalTeamMembers> IncidentsInternalTeamMembers { get; set; } = new List<IncidentsInternalTeamMembers>();

    public virtual ICollection<IncidentsLessonsLearnt> IncidentsLessonsLearnt { get; set; } = new List<IncidentsLessonsLearnt>();

    public virtual ICollection<IncidentsRPOLibraryLinkIncidents> IncidentsRPOLibraryLinkIncidents { get; set; } = new List<IncidentsRPOLibraryLinkIncidents>();

    public virtual ICollection<IncidentsRTOLibraryLinkIncidents> IncidentsRTOLibraryLinkIncidents { get; set; } = new List<IncidentsRTOLibraryLinkIncidents>();

    public virtual ICollection<IncidentsReports> IncidentsReports { get; set; } = new List<IncidentsReports>();

    public virtual ICollection<IncidentsSnapChartCausalFactors> IncidentsSnapChartCausalFactors { get; set; } = new List<IncidentsSnapChartCausalFactors>();

    public virtual ICollection<IncidentsSnapChartLog> IncidentsSnapChartLog { get; set; } = new List<IncidentsSnapChartLog>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementsOfNeed { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual AspNetUsers Owner { get; set; }

    public virtual AspNetUsers ReportingUser { get; set; }

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();

    public virtual ICollection<Incidents> IncidentChild { get; set; } = new List<Incidents>();

    public virtual ICollection<Incidents> IncidentParent { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsInternalTeamMembers> IncidentsFieldInvestigationInternalTeamMember { get; set; } = new List<IncidentsInternalTeamMembers>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<Risks> Risk { get; set; } = new List<Risks>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RiskOwnedRiskAutomatedControlTestBatch { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();
}