// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsRTOLibraryLinkIncidents
{
    public Guid IncidentsRTOLibraryId { get; set; }

    public Guid IncidentId { get; set; }

    public DateTime RTODt { get; set; }

    public string Comment { get; set; }

    public string CommentById { get; set; }

    public int RTOAchieved { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CommentBy { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Incidents Incident { get; set; }

    public virtual IncidentsRTOLibrary IncidentsRTOLibrary { get; set; }
}