// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsCannedBCPs
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid BCPLibraryId { get; set; }

    public Guid IncidentCategoryId { get; set; }

    public Guid IncidentSeverityId { get; set; }

    public int IncidentTypeId { get; set; }

    public int BCPAutoStart { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual BCPLibrary BCPLibrary { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual IncidentsCategories IncidentCategory { get; set; }

    public virtual IncidentsSeverities IncidentSeverity { get; set; }
}