// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsRTOLibrary
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public int IncidentTypeId { get; set; }

    public Guid IncidentCategoryId { get; set; }

    public Guid IncidentSeverityId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string RTODurationOffset { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual IncidentsCategories IncidentCategory { get; set; }

    public virtual IncidentsSeverities IncidentSeverity { get; set; }

    public virtual IncidentsRTOLibraryLinkIncidents IncidentsRTOLibraryLinkIncidents { get; set; }
}