// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsDivisionOwners
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public string UserId { get; set; }

    public int IncidentTypeId { get; set; }

    public Guid IncidentCategoryId { get; set; }

    public Guid IncidentSeverityId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual IncidentsCategories IncidentCategory { get; set; }

    public virtual IncidentsSeverities IncidentSeverity { get; set; }

    public virtual AspNetUsers User { get; set; }
}