// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsFieldInvestigations
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentId { get; set; }

    public string OwnerId { get; set; }

    public Guid IncidentFieldIvestigationCategoryAndFormId { get; set; }

    public string FieldInvestigationFormJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Incidents Incident { get; set; }

    public virtual IncidentsFieldInvestigationCategoriesAndForms IncidentFieldIvestigationCategoryAndForm { get; set; }

    public virtual ICollection<IncidentsFieldInvestigationSubmissionLog> IncidentsFieldInvestigationSubmissionLog { get; set; } = new List<IncidentsFieldInvestigationSubmissionLog>();

    public virtual AspNetUsers Owner { get; set; }
}