// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsFieldInvestigationExternalPartiesLinkIncidents
{
    public Guid IncidentsFieldInvestigationsExternalPartiesId { get; set; }

    public Guid IncidentId { get; set; }

    public virtual IncidentsExternalTeamMembers IncidentsFieldInvestigationsExternalParties { get; set; }
}