// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsStatementsOfNeed
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int Priority { get; set; }

    public int EndorsementDecision { get; set; }

    public DateTime EndorsementDate { get; set; }

    public string EndorsementCommentary { get; set; }

    public string EndorsementDecisionById { get; set; }

    public DateTime DueDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Incidents Incident { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}