// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsCategories
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<Incidents> Incidents { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsCannedBCPs> IncidentsCannedBCPs { get; set; } = new List<IncidentsCannedBCPs>();

    public virtual ICollection<IncidentsCannedReports> IncidentsCannedReports { get; set; } = new List<IncidentsCannedReports>();

    public virtual ICollection<IncidentsDivisionOwners> IncidentsDivisionOwners { get; set; } = new List<IncidentsDivisionOwners>();

    public virtual ICollection<IncidentsRPOLibrary> IncidentsRPOLibrary { get; set; } = new List<IncidentsRPOLibrary>();

    public virtual ICollection<IncidentsRTOLibrary> IncidentsRTOLibrary { get; set; } = new List<IncidentsRTOLibrary>();

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScope { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RisksControls> RisksControls { get; set; } = new List<RisksControls>();
}