// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsReports
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentId { get; set; }

    public Guid IncidentCannedReportsId { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Incidents Incident { get; set; }

    public virtual IncidentsCannedReports IncidentCannedReports { get; set; }

    public virtual ICollection<IncidentsReportsComments> IncidentsReportsComments { get; set; } = new List<IncidentsReportsComments>();
}