// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsEmergencyResponses
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentEmergencyResponseTypeId { get; set; }

    public Guid IncidentId { get; set; }

    public string Contacted { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Incidents Incident { get; set; }

    public virtual IncidentsEmergencyResponseTypes IncidentEmergencyResponseType { get; set; }
}