// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsFieldInvestigationSubmissionLog
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid IncidentsFieldInvestigationId { get; set; }

    public Guid IncidentsFieldIvestigationCategoryAndFormsId { get; set; }

    public string FieldInvestigationSubmissionJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual IncidentsFieldInvestigations IncidentsFieldInvestigation { get; set; }

    public virtual IncidentsFieldInvestigationCategoriesAndForms IncidentsFieldIvestigationCategoryAndForms { get; set; }
}