// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IncidentsFieldInvestigationCategoriesAndForms
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public int TypeId { get; set; }

    public Guid ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string FormJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CratedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<IncidentsFieldInvestigationSubmissionLog> IncidentsFieldInvestigationSubmissionLog { get; set; } = new List<IncidentsFieldInvestigationSubmissionLog>();

    public virtual ICollection<IncidentsFieldInvestigations> IncidentsFieldInvestigations { get; set; } = new List<IncidentsFieldInvestigations>();
}