// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class InternalAuditPlan
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public DateTime TargetStartDt { get; set; }

    public DateTime TargetEndDt { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Descirption { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual ICollection<InternalAuditPlanResources> InternalAuditPlanResources { get; set; } = new List<InternalAuditPlanResources>();

    public virtual AspNetUsers Owner { get; set; }
}