// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class InternalAudits
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid? InternalAuditPlanId { get; set; }

    public Guid DivisionId { get; set; }

    public string BusinessUnit { get; set; }

    public string BusinessValueProposition { get; set; }

    public DateTime TargetStartDt { get; set; }

    public DateTime TargetEndDt { get; set; }

    public DateTime ActualStartDt { get; set; }

    public DateTime? ActualEndDt { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double FTERequired { get; set; }

    public string OwnedRiskReviewSummary { get; set; }

    public string RiskScopeSummary { get; set; }

    public string InherentAndResidualRiskSummary { get; set; }

    public string ControlScopeSummary { get; set; }

    public string ControlDesignEffectivenessSummary { get; set; }

    public string ControlOperatingEffectivenessSummary { get; set; }

    public string OutcomeSummary { get; set; }

    public string BusinessUnitComments { get; set; }

    public string BusinessUnitCommentsById { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers BusinessUnitCommentsBy { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual ICollection<InternalAuditResources> InternalAuditResources { get; set; } = new List<InternalAuditResources>();

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<RisksStandardsActs> RiskStandardAct { get; set; } = new List<RisksStandardsActs>();
}