// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IssuesActionsTasksComments
{
    public Guid id { get; set; }

    public Guid IATID { get; set; }

    public string Comment { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public bool Enabled { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual IssuesActionsTasks IAT { get; set; }
}