// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IssuesActionTaskTypes
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public bool SystemType { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public bool Enabled { get; set; }

    public string BaseOwnerId { get; set; }

    public string DisplayId { get; set; }

    public virtual AspNetUsers BaseOwner { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();

    public virtual ICollection<IssuesActionsTasksDivisionOwnerOverride> IssuesActionsTasksDivisionOwnerOverride { get; set; } = new List<IssuesActionsTasksDivisionOwnerOverride>();
}