// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IssuesActionsTasks
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string AllocatedToId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Guid IATTypeId { get; set; }

    public DateTime DueDate { get; set; }

    public string Outcome { get; set; }

    public int IATCategory { get; set; }

    public string Contact { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public Guid DivisionId { get; set; }

    public Guid? UrgencyId { get; set; }

    public virtual AspNetUsers AllocatedTo { get; set; }

    public virtual ICollection<BusinessContinuityPlansLinkActionTasks> BusinessContinuityPlansLinkActionTasksIssuesActionsTasksAction { get; set; } = new List<BusinessContinuityPlansLinkActionTasks>();

    public virtual ICollection<BusinessContinuityPlansLinkActionTasks> BusinessContinuityPlansLinkActionTasksIssuesActionsTasksTask { get; set; } = new List<BusinessContinuityPlansLinkActionTasks>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual IssuesActionTaskTypes IATType { get; set; }

    public virtual ICollection<IssuesActionsTasksComments> IssuesActionsTasksComments { get; set; } = new List<IssuesActionsTasksComments>();

    public virtual ICollection<IssuesActionsTasksLinkToSelf> IssuesActionsTasksLinkToSelf { get; set; } = new List<IssuesActionsTasksLinkToSelf>();

    public virtual IssuesActionsTasksUrgencyAndOffset Urgency { get; set; }

    public virtual ICollection<AssetRegisterMaintenanceLogs> AssetRegisterMaintenanceLog { get; set; } = new List<AssetRegisterMaintenanceLogs>();

    public virtual ICollection<AssuranceAutomatedControlTestBatchRun> AssuranceAutomatedControlTestBatchRun { get; set; } = new List<AssuranceAutomatedControlTestBatchRun>();

    public virtual ICollection<BusinessContinuityPlans> BusinessContinuityPlan { get; set; } = new List<BusinessContinuityPlans>();

    public virtual ICollection<ComplaintsOrCompliments> ComplaintsOrCompliments { get; set; } = new List<ComplaintsOrCompliments>();

    public virtual ICollection<Credentials> Credentials { get; set; } = new List<Credentials>();

    public virtual ICollection<DocsItems> DocsItem { get; set; } = new List<DocsItems>();

    public virtual ICollection<DocsReviews> DocsReview { get; set; } = new List<DocsReviews>();

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();

    public virtual ICollection<ImprovementsObjectives> ImprovementObjective { get; set; } = new List<ImprovementsObjectives>();

    public virtual ICollection<Incidents> Incident { get; set; } = new List<Incidents>();

    public virtual ICollection<IncidentsStatementsOfNeed> IncidentsStatementOfNeed { get; set; } = new List<IncidentsStatementsOfNeed>();

    public virtual ICollection<InternalAudits> InternalAudit { get; set; } = new List<InternalAudits>();

    public virtual ICollection<RegulatoryEngagementsOutcomes> RegulatoryEngagementOutcome { get; set; } = new List<RegulatoryEngagementsOutcomes>();

    public virtual ICollection<RiskDiscoveryScopeInherentAndResidualAssessments> RiskDescoveryScopeInherentAndResidualAssessment { get; set; } = new List<RiskDiscoveryScopeInherentAndResidualAssessments>();

    public virtual ICollection<RiskDiscovery> RiskDiscovery { get; set; } = new List<RiskDiscovery>();

    public virtual ICollection<RiskDiscoveryControlScopeOperatingEffectiveness> RiskDiscoveryContorlScopeOperatingEffectiveness { get; set; } = new List<RiskDiscoveryControlScopeOperatingEffectiveness>();

    public virtual ICollection<RiskDiscoveryControlScope> RiskDiscoveryControlScope { get; set; } = new List<RiskDiscoveryControlScope>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScope { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RiskDiscoveryControlScopeDesignEffectiveness> RiskDiscoveryScopeDesignEffectiveness { get; set; } = new List<RiskDiscoveryControlScopeDesignEffectiveness>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RiskOwnedRiskAutomatedControlTestBatch { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();
}