// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class IssuesActionsTasksLinkToSelf
{
    public Guid IssueActionTypeParentId { get; set; }

    public Guid IssueActionTypeChildId { get; set; }

    public virtual IssuesActionsTasks IssueActionTypeParent { get; set; }
}