// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RegulatoryEngagementBody
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Web { get; set; }

    public string Address { get; set; }

    public string EngagementTypes { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<RegulatoryEngagementBodyContacts> RegulatoryEngagementBodyContacts { get; set; } = new List<RegulatoryEngagementBodyContacts>();

    public virtual ICollection<RegulatoryEngagements> RegulatoryEngagements { get; set; } = new List<RegulatoryEngagements>();
}