// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RegulatoryEngagementEventLog
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RegulatoryEngagementId { get; set; }

    public DateTime EventDt { get; set; }

    public int EventType { get; set; }

    public int EventCategory { get; set; }

    public string Description { get; set; }

    public string URL { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RegulatoryEngagements RegulatoryEngagement { get; set; }
}