// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RegulatoryEngagements
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RegulatoryEngagementBodyId { get; set; }

    public string OwnerId { get; set; }

    public DateTime StartDt { get; set; }

    public DateTime? TargetEndDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string Who { get; set; }

    public string What { get; set; }

    public DateTime WhenDt { get; set; }

    public Guid WhereDivisionId { get; set; }

    public string Why { get; set; }

    public string How { get; set; }

    public string EnforcableUndertaking { get; set; }

    public string PenaltyDescription { get; set; }

    public double? PenaltyAdvised { get; set; }

    public double? PenaltyPaid { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual RegulatoryEngagementBody RegulatoryEngagementBody { get; set; }

    public virtual ICollection<RegulatoryEngagementEventLog> RegulatoryEngagementEventLog { get; set; } = new List<RegulatoryEngagementEventLog>();

    public virtual ICollection<RegulatoryEngagementResources> RegulatoryEngagementResources { get; set; } = new List<RegulatoryEngagementResources>();

    public virtual ICollection<RegulatoryEngagementsOutcomes> RegulatoryEngagementsOutcomes { get; set; } = new List<RegulatoryEngagementsOutcomes>();

    public virtual Divisions WhereDivision { get; set; }

    public virtual ICollection<RegulatoryEngagementBodyContacts> RegulatoryEngagementBodyContact { get; set; } = new List<RegulatoryEngagementBodyContacts>();
}