// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRiskInherentAndResidualAssessmentSignOff
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskOwnedRiskInherentResidualAssessmentId { get; set; }

    public string UserId { get; set; }

    public string ConfirmationStatement { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }
}