// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksMatrixs
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int LikelihoodScale { get; set; }

    public int ConsequenceScale { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<Risks> Risks { get; set; } = new List<Risks>();

    public virtual ICollection<RisksMatirxsConcequenceLabels> RisksMatirxsConcequenceLabels { get; set; } = new List<RisksMatirxsConcequenceLabels>();

    public virtual ICollection<RisksMatirxsLikelihoodLabels> RisksMatirxsLikelihoodLabels { get; set; } = new List<RisksMatirxsLikelihoodLabels>();

    public virtual ICollection<RisksMatrixLikelihoodConsequenceFields> RisksMatrixLikelihoodConsequenceFields { get; set; } = new List<RisksMatrixLikelihoodConsequenceFields>();
}