// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRiskAutomatedControlTestDefinition
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid AssuranceProgramId { get; set; }

    public Guid AssuranceTemplateId { get; set; }

    public Guid RiskOwnedRiskId { get; set; }

    public Guid RiskControlId { get; set; }

    public int AutomatedControlTestTypeId { get; set; }

    public int Threshold { get; set; }

    public string TestJSON { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public string emailCC { get; set; }

    public string SMSCC { get; set; }

    public int? BatchSize { get; set; }

    public string TestType { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RisksControls RiskControl { get; set; }

    public virtual RisksOwnedRisk RiskOwnedRisk { get; set; }

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatch> RisksOwnedRiskAutomatedControlTestBatch { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatch>();
}