// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksControlSuggestions
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskId { get; set; }

    public string MyRole { get; set; }

    public string ProblemObserved { get; set; }

    public string CompletenessSuggestion { get; set; }

    public string AuthoritySuggestion { get; set; }

    public string RemedialCorrectionSuggestion { get; set; }

    public string SegregationOfDutiesSuggestion { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Risks Risk { get; set; }

    public virtual ICollection<RisksControlSuggestionComments> RisksControlSuggestionComments { get; set; } = new List<RisksControlSuggestionComments>();

    public virtual ICollection<RisksControls> RisksControls { get; set; } = new List<RisksControls>();
}