// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRiskInherentAndRedisualAssessment
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid OwnedRiskId { get; set; }

    public string InherentLikelihood { get; set; }

    public string InherentConsequence { get; set; }

    public string InherentImpact { get; set; }

    public string ResidualLikelihood { get; set; }

    public string ResidualConsequence { get; set; }

    public string ResidualImpact { get; set; }

    public string AssessmentSummary { get; set; }

    public int? AssessmentOutcome { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public DateTime? NextReviewDt { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RisksOwnedRisk OwnedRisk { get; set; }

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness> RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness>();

    public virtual ICollection<RisksOwnedRiskInherentAndResidualAssessmentUsers> RisksOwnedRiskInherentAndResidualAssessmentUsers { get; set; } = new List<RisksOwnedRiskInherentAndResidualAssessmentUsers>();

    public virtual ICollection<RisksOwnedRiskInherentResidualRiskAnalysis> RisksOwnedRiskInherentResidualRiskAnalysis { get; set; } = new List<RisksOwnedRiskInherentResidualRiskAnalysis>();

    public virtual ICollection<RisksOwnedRiskInherentRiskAnalysis> RisksOwnedRiskInherentRiskAnalysis { get; set; } = new List<RisksOwnedRiskInherentRiskAnalysis>();

    public virtual ICollection<RisksOwnedRiskResidualRiskAnalysis> RisksOwnedRiskResidualRiskAnalysis { get; set; } = new List<RisksOwnedRiskResidualRiskAnalysis>();

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();
}