// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksSuggestions
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public string OwnerId { get; set; }

    public string Title { get; set; }

    public string AsA { get; set; }

    public string ItMay { get; set; }

    public string ResultingIn { get; set; }

    public string ScenarioResponse { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<Risks> Risks { get; set; } = new List<Risks>();

    public virtual ICollection<RisksSuggestionComments> RisksSuggestionComments { get; set; } = new List<RisksSuggestionComments>();

    public virtual ICollection<RisksStandardsActs> RiskStandardAct { get; set; } = new List<RisksStandardsActs>();
}