// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRiskInherentRiskAnalysis
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RisksOwnedRiskInherentAndResidualAssessmentId { get; set; }

    public int TypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string URL { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RisksOwnedRiskInherentAndRedisualAssessment RisksOwnedRiskInherentAndResidualAssessment { get; set; }
}