// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class Risks
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskMatrixId { get; set; }

    public Guid? RiskSuggestionId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string AsA { get; set; }

    public string ItMay { get; set; }

    public string ResultingIn { get; set; }

    public string RATLikelihood { get; set; }

    public string RATConsequence { get; set; }

    public string RATImpact { get; set; }

    public string RATBGColor { get; set; }

    public string RATFGColor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScope { get; set; } = new List<RiskDiscoveryScope>();

    public virtual RisksMatrixs RiskMatrix { get; set; }

    public virtual RisksSuggestions RiskSuggestion { get; set; }

    public virtual ICollection<RisksControlSuggestions> RisksControlSuggestions { get; set; } = new List<RisksControlSuggestions>();

    public virtual ICollection<RisksControls> RisksControls { get; set; } = new List<RisksControls>();

    public virtual ICollection<RisksOwnedRisk> RisksOwnedRisk { get; set; } = new List<RisksOwnedRisk>();

    public virtual ICollection<Docs> Docs { get; set; } = new List<Docs>();

    public virtual ICollection<Incidents> Incident { get; set; } = new List<Incidents>();

    public virtual ICollection<RisksStandardsActs> RisksStandardsActs { get; set; } = new List<RisksStandardsActs>();
}