// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RiskDiscoveryControlScope
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskDiscoveryScopeId { get; set; }

    public int ExistingControl { get; set; }

    public Guid? RisksControlId { get; set; }

    public int SuitabilityCompleteness { get; set; }

    public string SuitabilityCompletenessComments { get; set; }

    public int SuitabilityAuthority { get; set; }

    public string SuitabilityAuthorityComments { get; set; }

    public int SuitabilityRemedialCorrection { get; set; }

    public string SuitabilityRemedialCorrectionComments { get; set; }

    public int SuitabilitySegregationOfDuties { get; set; }

    public string SuitabilitySegregationOfDutiesComments { get; set; }

    public string ControlAssessmentComments { get; set; }

    public string RiskMitigationCapacity { get; set; }

    public string ControlFailureAppetite { get; set; }

    public int EscalationPathIdentified { get; set; }

    public string EscalationPathComments { get; set; }

    public int ConfiguredAutomatedControlTesting { get; set; }

    public int ConfituredAutomatedBusinessContinuity { get; set; }

    public Guid? IncidentCategoryId { get; set; }

    public Guid? IncidentSeverityId { get; set; }

    public int? IncidentType { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual IncidentsCategories IncidentCategory { get; set; }

    public virtual IncidentsSeverities IncidentSeverity { get; set; }

    public virtual ICollection<RiskDiscoveryControlScopeDesignEffectiveness> RiskDiscoveryControlScopeDesignEffectiveness { get; set; } = new List<RiskDiscoveryControlScopeDesignEffectiveness>();

    public virtual RiskDiscoveryScope RiskDiscoveryScope { get; set; }

    public virtual ICollection<RiskDiscoveryScopeInherentAndResidualAssessments> RiskDiscoveryScopeInherentAndResidualAssessments { get; set; } = new List<RiskDiscoveryScopeInherentAndResidualAssessments>();

    public virtual RisksControls RisksControl { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}