// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksStandardsActs
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid? ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual ICollection<AssuranceSubmissionProcessedRisksStandardsActsWeightings> AssuranceSubmissionProcessedRisksStandardsActsWeightings { get; set; } = new List<AssuranceSubmissionProcessedRisksStandardsActsWeightings>();

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual ICollection<RisksStandardsActs> InverseParent { get; set; } = new List<RisksStandardsActs>();

    public virtual RisksStandardsActs Parent { get; set; }

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();

    public virtual ICollection<InternalAudits> InternalAudit { get; set; } = new List<InternalAudits>();

    public virtual ICollection<Risks> Risk { get; set; } = new List<Risks>();

    public virtual ICollection<RisksSuggestions> RiskSuggestion { get; set; } = new List<RisksSuggestions>();
}