// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRiskInherentAndResidualAssessmentControlEffectiveness
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskLibraryOwnedRiskInhereentAndResidualAssessmentId { get; set; }

    public Guid RiskControlId { get; set; }

    public string DETestMethodology { get; set; }

    public int DESampleSize { get; set; }

    public string DEEffectiveness { get; set; }

    public string OETestMethodology { get; set; }

    public int? OESampleSize { get; set; }

    public string OEEffectiveness { get; set; }

    public string Commentary { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RisksControls RiskControl { get; set; }

    public virtual RisksOwnedRiskInherentAndRedisualAssessment RiskLibraryOwnedRiskInhereentAndResidualAssessment { get; set; }
}