// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RiskDiscovery
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public string AccountableOwnerId { get; set; }

    public string AccountableOwnerComments { get; set; }

    public string BusinessUnit { get; set; }

    public string BusinessUnitFunction { get; set; }

    public int PoliciesIdentified { get; set; }

    public string PolicyComments { get; set; }

    public int ProcessesIdentified { get; set; }

    public string ProcessesComments { get; set; }

    public int WorkInstructionsIdentified { get; set; }

    public string WorkInstructionsComments { get; set; }

    public int PolicyExemptionsIdentified { get; set; }

    public string PolicyExemptionsComments { get; set; }

    public string RiskCultureStatement { get; set; }

    public string WhatIsRisk { get; set; }

    public string WhatAreYourRisks { get; set; }

    public string CretedById { get; set; }

    public DateTime CreeatdDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers AccountableOwner { get; set; }

    public virtual AspNetUsers CretedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual ICollection<RiskDiscoveryResources> RiskDiscoveryResources { get; set; } = new List<RiskDiscoveryResources>();

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScope { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<Improvements> Improvement { get; set; } = new List<Improvements>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}