// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RiskDiscoveryScopeInherentAndResidualAssessments
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskDiscoveryScopeId { get; set; }

    public string ReveiwHistory { get; set; }

    public string InherentRiskAssessmentQuality { get; set; }

    public string ResidualRiskAssessmentQuality { get; set; }

    public int ControlsDETested { get; set; }

    public int ControlsOETested { get; set; }

    public int? SignOffComplete { get; set; }

    public int? SignOffAppropriate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RiskDiscoveryControlScope RiskDiscoveryScope { get; set; }

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}