// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRiskAutomatedControlTestBatch
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskOwnedRiskAutomatedControlTestDefinitionId { get; set; }

    public DateTime BatchStartDt { get; set; }

    public DateTime? BatchEndDt { get; set; }

    public int TestsExecuted { get; set; }

    public int TestsPassed { get; set; }

    public int TestsFailed { get; set; }

    public int IssuesRaised { get; set; }

    public int IncidentsRaised { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RisksOwnedRiskAutomatedControlTestDefinition RiskOwnedRiskAutomatedControlTestDefinition { get; set; }

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes> RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes { get; set; } = new List<RisksOwnedRiskAutomatedControlTestBatchExecutedOutcomes>();

    public virtual ICollection<Incidents> Incident { get; set; } = new List<Incidents>();

    public virtual ICollection<IssuesActionsTasks> IssuesActionsTasks { get; set; } = new List<IssuesActionsTasks>();
}