// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksMatirxsConcequenceLabels
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid RiskMatrixId { get; set; }

    public int OrderId { get; set; }

    public string Label { get; set; }

    public string Measurement { get; set; }

    public string BGColor { get; set; }

    public string FGColor { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual RisksMatrixs RiskMatrix { get; set; }

    public virtual ICollection<RisksMatrixLikelihoodConsequenceFields> RisksMatrixLikelihoodConsequenceFields { get; set; } = new List<RisksMatrixLikelihoodConsequenceFields>();
}