// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class RisksOwnedRisk
{
    public Guid Id { get; set; }

    public string DisplayId { get; set; }

    public Guid DivisionId { get; set; }

    public Guid RiskId { get; set; }

    public string OwnerId { get; set; }

    public DateTime EffectiveDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string CreatedById { get; set; }

    public DateTime CreatedDt { get; set; }

    public int Status { get; set; }

    public virtual AspNetUsers CreatedBy { get; set; }

    public virtual Divisions Division { get; set; }

    public virtual AspNetUsers Owner { get; set; }

    public virtual Risks Risk { get; set; }

    public virtual ICollection<RiskDiscoveryScope> RiskDiscoveryScope { get; set; } = new List<RiskDiscoveryScope>();

    public virtual ICollection<RisksOwnedRiskAutomatedControlTestDefinition> RisksOwnedRiskAutomatedControlTestDefinition { get; set; } = new List<RisksOwnedRiskAutomatedControlTestDefinition>();

    public virtual ICollection<RisksOwnedRiskInherentAndRedisualAssessment> RisksOwnedRiskInherentAndRedisualAssessment { get; set; } = new List<RisksOwnedRiskInherentAndRedisualAssessment>();
}