// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WordCreationTester.Data.Models;

public partial class SSRSReportGroups
{
    public Guid Id { get; set; }

    public string GroupName { get; set; }

    public virtual ICollection<SSRSReportList> SSRSReportList { get; set; } = new List<SSRSReportList>();
}